package stock.batch.service.batch.marketclose.writer;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

import javax.sql.DataSource;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;

import stock.batch.service.testsupport.BatchTestDatabaseFactory;

import static org.assertj.core.api.Assertions.assertThat;

class MarketCloseRolloverWriterCashFlowTest {

    private JdbcTemplate jdbcTemplate;
    private MarketCloseRolloverWriter writer;

    @BeforeEach
    void setUp() {
        DataSource dataSource = BatchTestDatabaseFactory.createDataSource("close_cash_flow_watermark");
        jdbcTemplate = new JdbcTemplate(dataSource);
        createSchema();
        writer = new MarketCloseRolloverWriter(jdbcTemplate);
        insertAccount(1L, "user-a", "1000.00");
        insertAccount(2L, "user-b", "2000.00");
    }

    private void createSchema() {
        jdbcTemplate.execute("""
                create table stock_account(
                    id bigint primary key,
                    user_key varchar(64),
                    account_code varchar(32),
                    status varchar(20) not null,
                    participant_category varchar(30) not null default 'MANUAL_PARTICIPANT',
                    cash_balance decimal(19,2) not null,
                    created_at timestamp not null,
                    updated_at timestamp not null
                )
                """);
        jdbcTemplate.execute("""
                create table stock_account_cash_flow(
                    id bigint generated by default as identity primary key,
                    account_id bigint not null,
                    flow_type varchar(20) not null,
                    amount decimal(19,2) not null,
                    reason varchar(40) not null,
                    created_at timestamp not null
                )
                """);
        jdbcTemplate.execute("""
                create table stock_auto_participant(
                    user_key varchar(64) primary key,
                    profile_type varchar(40) not null
                )
                """);
        jdbcTemplate.execute("""
                create table stock_close_account_snapshot(
                    id bigint generated by default as identity primary key,
                    close_cycle_id bigint not null,
                    close_run_id bigint not null,
                    account_id bigint not null,
                    user_key varchar(64),
                    account_status varchar(20) not null,
                    participant_category varchar(30) not null default 'MANUAL_PARTICIPANT',
                    participant_profile_type varchar(40),
                    settlement_target boolean not null,
                    pre_cancel_cash decimal(19,2) not null,
                    pre_cancel_order_reserved_cash decimal(19,2) not null,
                    subscription_reserved_cash decimal(19,2) not null,
                    post_cancel_cash decimal(19,2),
                    external_net_cash_flow decimal(19,2) not null,
                    cash_flow_watermark_id bigint not null,
                    holding_market_value decimal(19,2) not null default 0,
                    holding_quantity bigint not null default 0,
                    reserved_sell_quantity bigint not null default 0,
                    holding_position_count bigint not null default 0,
                    reconciliation_status varchar(20) not null,
                    snapshot_at timestamp not null,
                    created_at timestamp not null,
                    unique(close_cycle_id, account_id)
                )
                """);
        jdbcTemplate.execute("""
                create table stock_holding_snapshot(
                    close_cycle_id bigint not null,
                    account_id bigint not null,
                    quantity bigint not null,
                    reserved_quantity bigint not null,
                    average_price decimal(19,2) not null,
                    evaluation_price decimal(19,2)
                )
                """);
        jdbcTemplate.execute("""
                create table stock_post_close_cycle(
                    id bigint primary key,
                    business_date date not null,
                    scope_type varchar(20) not null,
                    scope_key varchar(64) not null,
                    phase varchar(60) not null default 'LEDGER_FROZEN',
                    close_run_id bigint,
                    unique(business_date, scope_type, scope_key)
                )
                """);
        jdbcTemplate.execute("""
                create table stock_close_open_order_snapshot(
                    close_cycle_id bigint not null,
                    account_id bigint not null,
                    side varchar(10) not null,
                    reserved_cash decimal(19,2) not null
                )
                """);
        jdbcTemplate.execute("""
                create table stock_corporate_action_entitlement(
                    account_id bigint not null,
                    subscribed_cash_amount decimal(19,2),
                    status varchar(20) not null
                )
                """);
    }

    @Test
    void snapshotAccounts_nextCycle_readsOnlyCashFlowsAfterPreviousGlobalWatermark() {
        insertCashFlow(1L, "DEPOSIT", "1000.00", "MANUAL_DEPOSIT");
        insertCashFlow(2L, "DEPOSIT", "2000.00", "MANUAL_DEPOSIT");
        insertCashFlow(1L, "DEPOSIT", "100.00", "DIVIDEND_PAYMENT");
        long firstWatermark = writer.findCurrentCashFlowWatermark();
        insertPreviousSnapshot(1L, "1000.00", firstWatermark);
        insertPreviousSnapshot(2L, "2000.00", firstWatermark);

        insertCashFlow(1L, "WITHDRAW", "300.00", "MANUAL_WITHDRAW");
        insertCashFlow(1L, "DEPOSIT", "50.00", "DIVIDEND_PAYMENT");
        insertCashFlow(2L, "WITHDRAW", "500.00", "CAPITAL_INCREASE_SUBSCRIPTION");
        long secondWatermark = writer.findCurrentCashFlowWatermark();

        writer.snapshotAccountsForAccounts(
                11L,
                101L,
                LocalDateTime.parse("2026-07-16T18:00:00"),
                10L,
                writer.findCashFlowWatermark(10L),
                secondWatermark,
                List.of(1L, 2L)
        );

        assertThat(findSnapshots())
                .containsExactly(
                        new CashFlowSnapshot(10L, 1L, new BigDecimal("1000.00"), firstWatermark),
                        new CashFlowSnapshot(10L, 2L, new BigDecimal("2000.00"), firstWatermark),
                        new CashFlowSnapshot(11L, 1L, new BigDecimal("700.00"), secondWatermark),
                        new CashFlowSnapshot(11L, 2L, new BigDecimal("2000.00"), secondWatermark)
                );
    }

    @Test
    void snapshotAccounts_firstCycle_buildsInitialCashFlowBaseline() {
        insertCashFlow(1L, "DEPOSIT", "1000.00", "MANUAL_DEPOSIT");
        insertCashFlow(1L, "DEPOSIT", "100.00", "DIVIDEND_PAYMENT");
        long watermark = writer.findCurrentCashFlowWatermark();

        writer.snapshotAccountsForAccounts(
                10L,
                100L,
                LocalDateTime.parse("2026-07-15T18:00:00"),
                null,
                0L,
                watermark,
                List.of(1L, 2L)
        );

        assertThat(findSnapshots())
                .containsExactly(
                        new CashFlowSnapshot(10L, 1L, new BigDecimal("1000.00"), watermark),
                        new CashFlowSnapshot(10L, 2L, BigDecimal.ZERO.setScale(2), watermark)
                );
    }

    @Test
    void snapshotAccounts_freezesPersistedRoleAndExcludesListingAccountFromSettlementTarget() {
        jdbcTemplate.update(
                "update stock_account set participant_category = 'LISTING_UNDERWRITER' where id = 2"
        );

        writer.snapshotAccountsForAccounts(
                10L,
                100L,
                LocalDateTime.parse("2026-07-15T18:00:00"),
                null,
                0L,
                0L,
                List.of(1L, 2L)
        );

        assertThat(jdbcTemplate.queryForList(
                """
                select account_id, participant_category, settlement_target
                  from stock_close_account_snapshot
                 order by account_id
                """
        )).extracting(
                row -> row.get("PARTICIPANT_CATEGORY"),
                row -> row.get("SETTLEMENT_TARGET")
        ).containsExactly(
                org.assertj.core.groups.Tuple.tuple("MANUAL_PARTICIPANT", true),
                org.assertj.core.groups.Tuple.tuple("LISTING_UNDERWRITER", false)
        );
    }

    @Test
    void snapshotAccounts_autoParticipant_freezesProfileAtClose() {
        jdbcTemplate.update(
                "update stock_account set participant_category = 'AUTO_PARTICIPANT' where id = 1"
        );
        jdbcTemplate.update(
                "insert into stock_auto_participant(user_key, profile_type) values ('user-a', 'DAY_TRADER')"
        );

        writer.snapshotAccountsForAccounts(
                10L,
                100L,
                LocalDateTime.parse("2026-07-15T18:00:00"),
                null,
                0L,
                0L,
                List.of(1L)
        );

        assertThat(jdbcTemplate.queryForObject(
                "select participant_profile_type from stock_close_account_snapshot where account_id = 1",
                String.class
        )).isEqualTo("DAY_TRADER");
    }

    @Test
    void findPreviousFrozenFullMarketCycleId_outOfOrderIds_usesBusinessDatePredecessor() {
        insertCycle(100L, LocalDate.of(2026, 7, 14), 1_000L);
        insertCycle(300L, LocalDate.of(2026, 7, 16), 3_000L);
        insertCycle(400L, LocalDate.of(2026, 7, 13), 4_000L);
        insertCycle(200L, LocalDate.of(2026, 7, 15), 2_000L);

        assertThat(writer.findPreviousFrozenFullMarketCycleId(300L)).isEqualTo(200L);
    }

    @Test
    void findPreviousFrozenFullMarketCycleId_newerUnfrozenCycle_skipsIncompleteBaseline() {
        insertCycle(100L, LocalDate.of(2026, 7, 14), 1_000L, "LEDGER_FROZEN");
        insertCycle(200L, LocalDate.of(2026, 7, 15), 2_000L, "ORDER_ENTRY_CLOSED");
        insertCycle(300L, LocalDate.of(2026, 7, 16), 3_000L, "LEDGER_FROZEN");

        assertThat(writer.findPreviousFrozenFullMarketCycleId(300L)).isEqualTo(100L);
    }

    private void insertAccount(long id, String userKey, String cashBalance) {
        jdbcTemplate.update(
                """
                insert into stock_account(id, user_key, account_code, status, cash_balance, created_at, updated_at)
                values (?, ?, ?, 'ACTIVE', ?, current_timestamp, current_timestamp)
                """,
                id,
                userKey,
                "account-" + id,
                new BigDecimal(cashBalance)
        );
    }

    private void insertCashFlow(long accountId, String flowType, String amount, String reason) {
        jdbcTemplate.update(
                """
                insert into stock_account_cash_flow(account_id, flow_type, amount, reason, created_at)
                values (?, ?, ?, ?, current_timestamp)
                """,
                accountId,
                flowType,
                new BigDecimal(amount),
                reason
        );
    }

    private void insertPreviousSnapshot(long accountId, String externalNetCashFlow, long watermark) {
        jdbcTemplate.update(
                """
                insert into stock_close_account_snapshot(
                    close_cycle_id, close_run_id, account_id, user_key, account_status,
                    settlement_target, pre_cancel_cash, pre_cancel_order_reserved_cash,
                    subscription_reserved_cash, post_cancel_cash, external_net_cash_flow,
                    cash_flow_watermark_id, reconciliation_status, snapshot_at, created_at
                ) values (10, 100, ?, ?, 'ACTIVE', true, 0, 0, 0, 0, ?, ?, 'MATCHED', current_timestamp, current_timestamp)
                """,
                accountId,
                "user-" + accountId,
                new BigDecimal(externalNetCashFlow),
                watermark
        );
    }

    private void insertCycle(long id, LocalDate businessDate, long closeRunId) {
        insertCycle(id, businessDate, closeRunId, "LEDGER_FROZEN");
    }

    private void insertCycle(long id, LocalDate businessDate, long closeRunId, String phase) {
        jdbcTemplate.update(
                """
                    insert into stock_post_close_cycle(
                    id, business_date, scope_type, scope_key, phase, close_run_id
                ) values (?, ?, 'FULL_MARKET', 'ALL', ?, ?)
                """,
                id,
                businessDate,
                phase,
                closeRunId
        );
    }

    private List<CashFlowSnapshot> findSnapshots() {
        return jdbcTemplate.query(
                """
                select close_cycle_id, account_id, external_net_cash_flow, cash_flow_watermark_id
                  from stock_close_account_snapshot
                 order by close_cycle_id, account_id
                """,
                (resultSet, rowNumber) -> new CashFlowSnapshot(
                        resultSet.getLong("close_cycle_id"),
                        resultSet.getLong("account_id"),
                        resultSet.getBigDecimal("external_net_cash_flow"),
                        resultSet.getLong("cash_flow_watermark_id")
                )
        );
    }

    private record CashFlowSnapshot(
            long closeCycleId,
            long accountId,
            BigDecimal externalNetCashFlow,
            long cashFlowWatermarkId
    ) {
    }
}
