package stock.batch.service.batch.marketclose.writer;

import static org.assertj.core.api.Assertions.assertThat;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.UUID;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

class MarketCloseRolloverWriterPositionStateTest {

    private JdbcTemplate jdbcTemplate;
    private MarketCloseRolloverWriter writer;

    @BeforeEach
    void setUp() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:position_state_" + UUID.randomUUID()
                        + ";MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE",
                "sa",
                ""
        );
        jdbcTemplate = new JdbcTemplate(dataSource);
        jdbcTemplate.execute("""
                create table stock_auto_participant_position_state (
                    account_id bigint not null,
                    symbol varchar(20) not null,
                    position_opened_business_date date not null,
                    holding_trading_days int not null,
                    average_down_rounds int not null,
                    last_average_down_business_date date,
                    peak_close_price decimal(19,2) not null,
                    last_seen_business_date date not null,
                    updated_at timestamp not null,
                    primary key(account_id, symbol),
                    constraint chk_holding_trading_days check (holding_trading_days > 0)
                )
                """);
        jdbcTemplate.execute("""
                create table stock_auto_participant_performance_state (
                    account_id bigint not null primary key,
                    recent_profitable_trading_days int not null default 0,
                    recent_closed_trading_days int not null default 0,
                    last_seen_business_date date not null,
                    updated_at timestamp not null
                )
                """);
        jdbcTemplate.execute("""
                create table stock_execution_account_day_summary (
                    simulation_trade_date date not null,
                    account_id bigint not null,
                    sell_quantity bigint not null,
                    realized_profit decimal(19,2) not null,
                    primary key(simulation_trade_date, account_id)
                )
                """);
        jdbcTemplate.execute("""
                create table stock_close_account_snapshot (
                    close_cycle_id bigint not null,
                    account_id bigint not null,
                    user_key varchar(80),
                    participant_category varchar(30) not null,
                    participant_profile_type varchar(40)
                )
                """);
        jdbcTemplate.execute("""
                create table stock_holding_snapshot (
                    close_cycle_id bigint not null,
                    account_id bigint not null,
                    symbol varchar(20) not null,
                    quantity bigint not null,
                    average_price decimal(19,2) not null,
                    evaluation_price decimal(19,2)
                )
                """);
        jdbcTemplate.execute("""
                create table stock_execution_daily_account_snapshot (
                    close_run_id bigint not null,
                    account_id bigint not null,
                    symbol varchar(20) not null,
                    buy_quantity bigint not null
                )
                """);
        jdbcTemplate.execute("""
                create table stock_execution (
                    id bigint generated by default as identity primary key,
                    account_id bigint not null,
                    symbol varchar(20) not null,
                    side varchar(10) not null,
                    quantity bigint not null,
                    source varchar(30) not null,
                    executed_at timestamp not null
                )
                """);
        writer = new MarketCloseRolloverWriter(jdbcTemplate);
    }

    @Test
    void rebuildAutoParticipantPositionState_retryIsIdempotentAndCloseRemovesMemory() {
        LocalDate day1 = LocalDate.of(2027, 1, 18);
        insertFrozenPosition(1L, 11L, day1, new BigDecimal("100.00"), new BigDecimal("105.00"), 0L);
        insertClosedTradingDay(day1, "100.00");

        writer.rebuildAutoParticipantPositionState(1L, 11L, day1, day1.atTime(18, 20));

        assertState(day1, 1, 0, null, "105.00", day1);

        LocalDate day2 = day1.plusDays(1);
        markAverageDownDecision(day2);
        insertFrozenPosition(2L, 12L, day2, new BigDecimal("110.00"), new BigDecimal("120.00"), 5L);
        insertClosedTradingDay(day2, "-20.00");
        writer.rebuildAutoParticipantPositionState(2L, 12L, day2, day2.atTime(18, 20));
        writer.rebuildAutoParticipantPositionState(2L, 12L, day2, day2.atTime(18, 21));

        assertState(day1, 2, 1, day2, "120.00", 1, 2, day2);

        jdbcTemplate.update(
                "insert into stock_close_account_snapshot(close_cycle_id, account_id, user_key, participant_category, participant_profile_type) values (3, 10, 'auto-10', 'AUTO_PARTICIPANT', 'AVERAGE_DOWN_BUYER')"
        );
        writer.rebuildAutoParticipantPositionState(3L, 13L, day2.plusDays(1), day2.plusDays(1).atTime(18, 20));

        Integer remaining = jdbcTemplate.queryForObject(
                "select count(*) from stock_auto_participant_position_state",
                Integer.class
        );
        assertThat(remaining).isZero();
    }

    @Test
    void rebuildAutoParticipantPositionState_newIntradayState_countsFirstFilledAverageDownOnce() {
        LocalDate businessDate = LocalDate.of(2027, 1, 18);
        jdbcTemplate.update(
                """
                insert into stock_auto_participant_position_state
                values (10, 'STOCK001', ?, 1, 0, ?, 110, ?, ?)
                """,
                businessDate,
                businessDate,
                businessDate,
                businessDate.atTime(10, 15)
        );
        insertFrozenPosition(1L, 11L, businessDate, new BigDecimal("110.00"), new BigDecimal("90.00"), 5L);
        insertClosedTradingDay(businessDate, "-20.00");

        writer.rebuildAutoParticipantPositionState(1L, 11L, businessDate, businessDate.atTime(18, 20));
        writer.rebuildAutoParticipantPositionState(1L, 11L, businessDate, businessDate.atTime(18, 21));

        assertState(businessDate, 1, 1, businessDate, "110.00", 0, 1, businessDate);
    }

    @Test
    void rebuildAutoParticipantPositionState_buyWithoutAverageDownMarker_doesNotConsumeV2Round() {
        LocalDate day1 = LocalDate.of(2027, 1, 18);
        insertFrozenPosition(1L, 11L, day1, new BigDecimal("100.00"), new BigDecimal("105.00"), 0L);
        insertClosedTradingDay(day1, "10.00");
        writer.rebuildAutoParticipantPositionState(1L, 11L, day1, day1.atTime(18, 20));

        LocalDate day2 = day1.plusDays(1);
        insertFrozenPosition(2L, 12L, day2, new BigDecimal("110.00"), new BigDecimal("90.00"), 5L);
        insertClosedTradingDay(day2, "-20.00");

        writer.rebuildAutoParticipantPositionState(2L, 12L, day2, day2.atTime(18, 20));

        assertState(day1, 2, 0, null, "105.00", 1, 2, day2);
    }

    @Test
    void rebuildAutoParticipantPositionState_sameDayFullExit_removesPositionMemoryImmediately() {
        LocalDate businessDate = LocalDate.of(2027, 1, 18);
        jdbcTemplate.update(
                """
                insert into stock_auto_participant_position_state
                values (10, 'STOCK001', ?, 1, 0, null, 110, ?, ?)
                """,
                businessDate,
                businessDate,
                businessDate.atTime(10, 15)
        );
        jdbcTemplate.update(
                "insert into stock_close_account_snapshot(close_cycle_id, account_id, user_key, participant_category, participant_profile_type) values (1, 10, 'auto-10', 'AUTO_PARTICIPANT', 'LONG_TERM_HOLDER')"
        );

        writer.rebuildAutoParticipantPositionState(1L, 11L, businessDate, businessDate.atTime(18, 20));

        Integer remaining = jdbcTemplate.queryForObject(
                "select count(*) from stock_auto_participant_position_state",
                Integer.class
        );
        assertThat(remaining).isZero();
    }

    @Test
    void rebuildAutoParticipantPositionState_intradayFullExitAndReentry_resetsHoldingMemory() {
        LocalDate day1 = LocalDate.of(2027, 1, 18);
        insertFrozenPosition(1L, 11L, day1, new BigDecimal("100.00"), new BigDecimal("120.00"), 0L);
        insertClosedTradingDay(day1, "10.00");
        writer.rebuildAutoParticipantPositionState(1L, 11L, day1, day1.atTime(18, 20));

        LocalDate day2 = day1.plusDays(1);
        insertFrozenPosition(2L, 12L, day2, new BigDecimal("90.00"), new BigDecimal("95.00"), 10L);
        insertClosedTradingDay(day2, "-5.00");
        insertExecution("SELL", 10L, day2.atTime(9, 0));
        insertExecution("BUY", 10L, day2.atTime(10, 0));

        writer.rebuildAutoParticipantPositionState(2L, 12L, day2, day2.atTime(18, 20));
        writer.rebuildAutoParticipantPositionState(2L, 12L, day2, day2.atTime(18, 21));

        assertState(day2, 1, 0, null, "95.00", 1, 2, day2);
    }

    @Test
    void rebuildAutoParticipantPositionState_buyBeforeSellWithoutFlatPosition_keepsHoldingMemory() {
        LocalDate day1 = LocalDate.of(2027, 1, 18);
        insertFrozenPosition(1L, 11L, day1, new BigDecimal("100.00"), new BigDecimal("120.00"), 0L);
        insertClosedTradingDay(day1, "10.00");
        writer.rebuildAutoParticipantPositionState(1L, 11L, day1, day1.atTime(18, 20));

        LocalDate day2 = day1.plusDays(1);
        insertFrozenPosition(2L, 12L, day2, new BigDecimal("105.00"), new BigDecimal("110.00"), 10L);
        insertClosedTradingDay(day2, "5.00");
        insertExecution("BUY", 10L, day2.atTime(9, 0));
        insertExecution("SELL", 10L, day2.atTime(10, 0));

        writer.rebuildAutoParticipantPositionState(2L, 12L, day2, day2.atTime(18, 20));

        assertState(day1, 2, 0, null, "120.00", 2, 2, day2);
    }

    private void insertFrozenPosition(
            long cycleId,
            long closeRunId,
            LocalDate businessDate,
            BigDecimal averagePrice,
            BigDecimal evaluationPrice,
            long buyQuantity
    ) {
        jdbcTemplate.update(
                "insert into stock_close_account_snapshot(close_cycle_id, account_id, user_key, participant_category, participant_profile_type) values (?, 10, 'auto-10', 'AUTO_PARTICIPANT', 'AVERAGE_DOWN_BUYER')",
                cycleId
        );
        jdbcTemplate.update(
                "insert into stock_holding_snapshot(close_cycle_id, account_id, symbol, quantity, average_price, evaluation_price) values (?, 10, 'STOCK001', 10, ?, ?)",
                cycleId,
                averagePrice,
                evaluationPrice
        );
        if (buyQuantity > 0) {
            jdbcTemplate.update(
                    "insert into stock_execution_daily_account_snapshot(close_run_id, account_id, symbol, buy_quantity) values (?, 10, 'STOCK001', ?)",
                    closeRunId,
                    buyQuantity
            );
        }
    }

    private void insertClosedTradingDay(LocalDate businessDate, String realizedProfit) {
        jdbcTemplate.update(
                "insert into stock_execution_account_day_summary(simulation_trade_date, account_id, sell_quantity, realized_profit) values (?, 10, 1, ?)",
                businessDate,
                new BigDecimal(realizedProfit)
        );
    }

    private void markAverageDownDecision(LocalDate businessDate) {
        jdbcTemplate.update(
                """
                update stock_auto_participant_position_state
                   set last_average_down_business_date = ?,
                       updated_at = ?
                 where account_id = 10
                   and symbol = 'STOCK001'
                """,
                businessDate,
                businessDate.atTime(10, 15)
        );
    }

    private void insertExecution(String side, long quantity, LocalDateTime executedAt) {
        jdbcTemplate.update(
                "insert into stock_execution(account_id, symbol, side, quantity, source, executed_at) values (10, 'STOCK001', ?, ?, 'INTERNAL_ORDER_BOOK', ?)",
                side,
                quantity,
                executedAt
        );
    }

    private void assertState(
            LocalDate openedDate,
            int holdingDays,
            int averageDownRounds,
            LocalDate lastAverageDownDate,
            String peakPrice,
            int profitableTradingDays,
            int closedTradingDays,
            LocalDate lastSeenDate
    ) {
        jdbcTemplate.queryForObject(
                "select * from stock_auto_participant_position_state where account_id = 10 and symbol = 'STOCK001'",
                (rs, rowNum) -> {
                    assertThat(rs.getObject("position_opened_business_date", LocalDate.class)).isEqualTo(openedDate);
                    assertThat(rs.getInt("holding_trading_days")).isEqualTo(holdingDays);
                    assertThat(rs.getInt("average_down_rounds")).isEqualTo(averageDownRounds);
                    assertThat(rs.getObject("last_average_down_business_date", LocalDate.class)).isEqualTo(lastAverageDownDate);
                    assertThat(rs.getBigDecimal("peak_close_price")).isEqualByComparingTo(peakPrice);
                    assertThat(rs.getObject("last_seen_business_date", LocalDate.class)).isEqualTo(lastSeenDate);
                    return 1;
                }
        );
        jdbcTemplate.queryForObject(
                "select * from stock_auto_participant_performance_state where account_id = 10",
                (rs, rowNum) -> {
                    assertThat(rs.getInt("recent_profitable_trading_days")).isEqualTo(profitableTradingDays);
                    assertThat(rs.getInt("recent_closed_trading_days")).isEqualTo(closedTradingDays);
                    assertThat(rs.getObject("last_seen_business_date", LocalDate.class)).isEqualTo(lastSeenDate);
                    return 1;
                }
        );
    }

    private void assertState(
            LocalDate openedDate,
            int holdingDays,
            int averageDownRounds,
            LocalDate lastAverageDownDate,
            String peakPrice,
            LocalDate lastSeenDate
    ) {
        assertState(
                openedDate,
                holdingDays,
                averageDownRounds,
                lastAverageDownDate,
                peakPrice,
                1,
                1,
                lastSeenDate
        );
    }
}
