spring:
  config:
    activate:
      on-profile: local-direct
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: false

eureka:
  client:
    enabled: false
    registerWithEureka: false
    fetchRegistry: false
