package stock.batch.service.batch.automarket.model;

import java.math.BigDecimal;

public record AutoParticipantProfileConfig(
        AutoParticipantProfileType profileType,
        AutoParticipantBehaviorModelVersion behaviorModelVersion,
        BigDecimal newsWeight,
        BigDecimal momentumWeight,
        BigDecimal contrarianWeight,
        BigDecimal lossAversionWeight,
        BigDecimal herdingWeight,
        BigDecimal marketMakingWeight,
        BigDecimal overconfidenceWeight,
        BigDecimal noiseWeight,
        BigDecimal panicSellWeight,
        BigDecimal dipBuyWeight,
        BigDecimal orderMultiplier,
        BigDecimal decisionFrequencyMultiplier,
        BigDecimal ordersPerDecisionMultiplier,
        BigDecimal aggressionMultiplier,
        BigDecimal pricePressureSensitivity,
        BigDecimal orderTtlMultiplier,
        BigDecimal quantityMultiplier,
        BigDecimal holdingPatienceWeight,
        BigDecimal deepLossHoldWeight,
        BigDecimal profitTakingWeight,
        String pricingMode,
        String exitMode,
        String inventoryMode,
        BigDecimal recurringDepositAmount,
        BigDecimal recurringDepositIntervalValue,
        RecurringCashIntervalUnit recurringDepositIntervalUnit,
        Integer recurringDepositIntervalDays
) {
    public AutoParticipantProfileConfig(
            AutoParticipantProfileType profileType,
            BigDecimal newsWeight,
            BigDecimal momentumWeight,
            BigDecimal contrarianWeight,
            BigDecimal lossAversionWeight,
            BigDecimal herdingWeight,
            BigDecimal marketMakingWeight,
            BigDecimal overconfidenceWeight,
            BigDecimal noiseWeight,
            BigDecimal panicSellWeight,
            BigDecimal dipBuyWeight,
            BigDecimal orderMultiplier,
            BigDecimal decisionFrequencyMultiplier,
            BigDecimal ordersPerDecisionMultiplier,
            BigDecimal aggressionMultiplier,
            BigDecimal pricePressureSensitivity,
            BigDecimal orderTtlMultiplier,
            BigDecimal quantityMultiplier,
            BigDecimal holdingPatienceWeight,
            BigDecimal deepLossHoldWeight,
            BigDecimal profitTakingWeight,
            String pricingMode,
            String exitMode,
            String inventoryMode,
            BigDecimal recurringDepositAmount,
            BigDecimal recurringDepositIntervalValue,
            RecurringCashIntervalUnit recurringDepositIntervalUnit,
            Integer recurringDepositIntervalDays
    ) {
        this(
                profileType,
                AutoParticipantBehaviorModelVersion.V2,
                newsWeight,
                momentumWeight,
                contrarianWeight,
                lossAversionWeight,
                herdingWeight,
                marketMakingWeight,
                overconfidenceWeight,
                noiseWeight,
                panicSellWeight,
                dipBuyWeight,
                orderMultiplier,
                decisionFrequencyMultiplier,
                ordersPerDecisionMultiplier,
                aggressionMultiplier,
                pricePressureSensitivity,
                orderTtlMultiplier,
                quantityMultiplier,
                holdingPatienceWeight,
                deepLossHoldWeight,
                profitTakingWeight,
                pricingMode,
                exitMode,
                inventoryMode,
                recurringDepositAmount,
                recurringDepositIntervalValue,
                recurringDepositIntervalUnit,
                recurringDepositIntervalDays
        );
    }
}
