CREATE TABLE IF NOT EXISTS stock_batch_job_control (
  job_name VARCHAR(100) NOT NULL PRIMARY KEY,
  runtime_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  scheduler_configured BOOLEAN NOT NULL DEFAULT TRUE,
  updated_by VARCHAR(64),
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  CONSTRAINT chk_stock_batch_job_control_name CHECK (job_name <> '')
);

CREATE TABLE IF NOT EXISTS stock_batch_job_lock (
  job_name VARCHAR(100) NOT NULL PRIMARY KEY,
  lock_owner VARCHAR(128) NOT NULL,
  locked_until TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  CONSTRAINT chk_stock_batch_job_lock_name CHECK (job_name <> ''),
  CONSTRAINT chk_stock_batch_job_lock_owner CHECK (lock_owner <> '')
);

CREATE TABLE IF NOT EXISTS stock_batch_job_signal (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  signal_type VARCHAR(60) NOT NULL,
  job_name VARCHAR(100) NOT NULL,
  execution_mode VARCHAR(120) NOT NULL,
  symbol VARCHAR(20),
  payload_json CLOB,
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  requested_by VARCHAR(64),
  requested_at TIMESTAMP NOT NULL,
  requested_business_date DATE,
  requested_session_epoch BIGINT,
  expected_cycle_id BIGINT,
  eligible_at TIMESTAMP,
  next_attempt_at TIMESTAMP NOT NULL,
  attempt_count INT NOT NULL DEFAULT 0,
  max_attempts INT NOT NULL DEFAULT 8,
  claim_token VARCHAR(64),
  lease_until TIMESTAMP,
  failure_class VARCHAR(40),
  picked_at TIMESTAMP,
  completed_at TIMESTAMP,
  processed_count INT,
  message VARCHAR(500),
  error_message VARCHAR(1000),
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  CONSTRAINT chk_stock_batch_job_signal_type CHECK (signal_type <> ''),
  CONSTRAINT chk_stock_batch_job_signal_job CHECK (job_name <> ''),
  CONSTRAINT chk_stock_batch_job_signal_mode CHECK (execution_mode <> ''),
  CONSTRAINT chk_stock_batch_job_signal_status CHECK (
    CASE `status`
      WHEN 'PENDING' THEN 1
      WHEN 'DEFERRED' THEN 1
      WHEN 'PROCESSING' THEN 1
      WHEN 'COMPLETED' THEN 1
      WHEN 'FAILED' THEN 1
      WHEN 'DEAD_LETTER' THEN 1
      ELSE 0
    END = 1
  ),
  CONSTRAINT chk_stock_batch_job_signal_attempt_count CHECK (attempt_count >= 0),
  CONSTRAINT chk_stock_batch_job_signal_max_attempts CHECK (max_attempts > 0),
  CONSTRAINT chk_stock_batch_job_signal_epoch CHECK (requested_session_epoch IS NULL OR requested_session_epoch > 0)
);

CREATE INDEX IF NOT EXISTS idx_stock_batch_job_signal_status_time ON stock_batch_job_signal(status, requested_at, id);
CREATE INDEX IF NOT EXISTS idx_stock_batch_job_signal_job_status ON stock_batch_job_signal(job_name, status, requested_at);
CREATE INDEX IF NOT EXISTS idx_stock_batch_job_signal_claim ON stock_batch_job_signal(status, next_attempt_at, eligible_at, id);
CREATE INDEX IF NOT EXISTS idx_stock_batch_job_signal_lease ON stock_batch_job_signal(status, lease_until, id);
CREATE INDEX IF NOT EXISTS idx_stock_batch_job_signal_cycle ON stock_batch_job_signal(expected_cycle_id, status, id);
CREATE INDEX IF NOT EXISTS idx_stock_batch_job_signal_cycle_id ON stock_batch_job_signal(expected_cycle_id, id);

CREATE TABLE IF NOT EXISTS stock_simulation_clock (
  clock_id VARCHAR(40) NOT NULL PRIMARY KEY,
  base_simulation_date DATE NOT NULL,
  real_seconds_per_simulation_day INT NOT NULL,
  accumulated_real_seconds BIGINT NOT NULL DEFAULT 0,
  running BOOLEAN NOT NULL DEFAULT FALSE,
  last_started_at TIMESTAMP,
  last_heartbeat_at TIMESTAMP,
  timezone VARCHAR(50) NOT NULL DEFAULT 'Asia/Seoul',
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  CONSTRAINT chk_stock_simulation_clock_id CHECK (clock_id <> ''),
  CONSTRAINT chk_stock_simulation_clock_day_seconds CHECK (real_seconds_per_simulation_day > 0),
  CONSTRAINT chk_stock_simulation_clock_accumulated CHECK (accumulated_real_seconds >= 0),
  CONSTRAINT chk_stock_simulation_clock_running_dates CHECK (
    running = FALSE OR (last_started_at IS NOT NULL AND last_heartbeat_at IS NOT NULL)
  )
);

CREATE TABLE IF NOT EXISTS stock_account (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_key VARCHAR(64) UNIQUE,
  account_code VARCHAR(32) UNIQUE,
  recovery_code_hash VARCHAR(128),
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  participant_category VARCHAR(30) NOT NULL DEFAULT 'MANUAL_PARTICIPANT',
  cash_balance DECIMAL(19,2) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  detached_at TIMESTAMP,
  reconnected_at TIMESTAMP,
  recovery_expires_at TIMESTAMP,
  purge_after TIMESTAMP,
  previous_user_key_hash VARCHAR(128),
  CONSTRAINT chk_stock_account_cash_non_negative CHECK (cash_balance >= 0),
  CONSTRAINT chk_stock_account_status_valid CHECK (CASE `status` WHEN 'ACTIVE' THEN 1 WHEN 'DETACHED' THEN 1 WHEN 'CLOSED' THEN 1 ELSE 0 END = 1),
  CONSTRAINT chk_stock_account_participant_category CHECK (
    CASE `participant_category`
      WHEN 'MANUAL_PARTICIPANT' THEN 1
      WHEN 'AUTO_PARTICIPANT' THEN 1
      WHEN 'LISTING_UNDERWRITER' THEN 1
      ELSE 0
    END = 1
  ),
  CONSTRAINT chk_stock_account_detached_user_scope CHECK (status <> 'DETACHED' OR user_key IS NULL),
  CONSTRAINT chk_stock_account_recovery_window CHECK (
    recovery_expires_at IS NULL OR purge_after IS NULL OR purge_after >= recovery_expires_at
  )
);

CREATE INDEX IF NOT EXISTS idx_stock_account_status_purge ON stock_account(status, purge_after);
CREATE INDEX IF NOT EXISTS idx_stock_account_status_id ON stock_account(status, id);
CREATE INDEX IF NOT EXISTS idx_stock_account_status_participant_id ON stock_account(status, participant_category, id);

CREATE TABLE IF NOT EXISTS stock_account_cash_flow (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id BIGINT NOT NULL,
  flow_type VARCHAR(20) NOT NULL,
  amount DECIMAL(19,2) NOT NULL,
  reason VARCHAR(40) NOT NULL,
  created_by VARCHAR(64),
  corporate_action_id BIGINT,
  corporate_action_entitlement_id BIGINT,
  effective_business_date DATE,
  created_at TIMESTAMP NOT NULL,
  CONSTRAINT chk_stock_account_cash_flow_amount CHECK (amount > 0)
);

CREATE INDEX IF NOT EXISTS idx_stock_account_cash_flow_account_time ON stock_account_cash_flow(account_id, created_at, id);
CREATE INDEX IF NOT EXISTS idx_stock_account_cash_flow_account_id ON stock_account_cash_flow(account_id, id);
CREATE INDEX IF NOT EXISTS idx_stock_account_cash_flow_account_reason_creator_time ON stock_account_cash_flow(account_id, reason, created_by, created_at, id);
CREATE INDEX IF NOT EXISTS idx_stock_account_cash_flow_account_type_reason_time ON stock_account_cash_flow(account_id, flow_type, reason, created_at, id);
CREATE INDEX IF NOT EXISTS idx_stock_account_cash_flow_time ON stock_account_cash_flow(created_at, id);
CREATE INDEX IF NOT EXISTS idx_stock_account_cash_flow_corporate_action ON stock_account_cash_flow(corporate_action_id, effective_business_date, account_id, id);

CREATE TABLE IF NOT EXISTS stock_auto_participant_cash_flow_run (
  run_key VARCHAR(160) NOT NULL PRIMARY KEY,
  operation VARCHAR(20) NOT NULL,
  last_account_id BIGINT NOT NULL DEFAULT 0,
  processed_count BIGINT NOT NULL DEFAULT 0,
  completed_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  CONSTRAINT chk_stock_auto_participant_cash_flow_run_operation CHECK (operation IN ('SCHEDULED', 'MANUAL')),
  CONSTRAINT chk_stock_auto_participant_cash_flow_run_cursor CHECK (last_account_id >= 0),
  CONSTRAINT chk_stock_auto_participant_cash_flow_run_count CHECK (processed_count >= 0)
);

CREATE INDEX IF NOT EXISTS idx_stock_auto_participant_cash_flow_run_completed
  ON stock_auto_participant_cash_flow_run(completed_at, run_key);

CREATE TABLE IF NOT EXISTS stock_instrument (
  symbol VARCHAR(20) NOT NULL PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  market VARCHAR(20) NOT NULL,
  enabled BOOLEAN NOT NULL,
  created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS stock_order_book_instrument (
  symbol VARCHAR(20) NOT NULL PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  market VARCHAR(20) NOT NULL,
  initial_price DECIMAL(19,2) NOT NULL,
  issued_shares BIGINT NOT NULL,
  tradable_shares BIGINT NOT NULL,
  tick_size DECIMAL(19,2) NOT NULL DEFAULT 1.00,
  price_limit_rate DECIMAL(5,2) NOT NULL DEFAULT 30.00,
  enabled BOOLEAN NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  CONSTRAINT chk_stock_order_book_instrument_initial_price CHECK (initial_price > 0),
  CONSTRAINT chk_stock_order_book_instrument_issued_shares CHECK (issued_shares > 0),
  CONSTRAINT chk_stock_order_book_instrument_tradable_shares CHECK (tradable_shares >= 0 AND tradable_shares <= issued_shares),
  CONSTRAINT chk_stock_order_book_instrument_tick_size CHECK (tick_size > 0),
  CONSTRAINT chk_stock_order_book_instrument_price_limit_rate CHECK (price_limit_rate > 0 AND price_limit_rate <= 100)
);

CREATE INDEX IF NOT EXISTS idx_stock_order_book_instrument_enabled ON stock_order_book_instrument(enabled, symbol);

CREATE TABLE IF NOT EXISTS stock_corporate_action (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  symbol VARCHAR(20) NOT NULL,
  action_type VARCHAR(40) NOT NULL,
  share_quantity BIGINT,
  issue_price DECIMAL(19,2),
  dividend_amount DECIMAL(19,2),
  status VARCHAR(30) NOT NULL DEFAULT 'ANNOUNCED',
  base_price DECIMAL(19,2),
  theoretical_ex_rights_price DECIMAL(19,2),
  ex_rights_date DATE,
  record_date DATE,
  entitlement_close_cycle_id BIGINT,
  entitlement_close_run_id BIGINT,
  payment_date DATE,
  listing_date DATE,
  delisting_date DATE,
  offering_type VARCHAR(40),
  subscription_start_date DATE,
  subscription_end_date DATE,
  delisting_treatment VARCHAR(30),
  applied_at TIMESTAMP,
  paid_at TIMESTAMP,
  listed_at TIMESTAMP,
  split_from INT,
  split_to INT,
  description VARCHAR(255),
  created_at TIMESTAMP NOT NULL,
  CONSTRAINT chk_stock_corporate_action_type_valid CHECK (CASE `action_type` WHEN 'INITIAL_ISSUE' THEN 1 WHEN 'PAID_IN_CAPITAL_INCREASE' THEN 1 WHEN 'STOCK_SPLIT' THEN 1 WHEN 'CASH_DIVIDEND' THEN 1 WHEN 'BONUS_ISSUE' THEN 1 WHEN 'STOCK_DIVIDEND' THEN 1 WHEN 'DELISTING' THEN 1 ELSE 0 END = 1),
  CONSTRAINT chk_stock_corporate_action_status_valid CHECK (CASE `status` WHEN 'ANNOUNCED' THEN 1 WHEN 'EX_RIGHTS_APPLIED' THEN 1 WHEN 'PAID' THEN 1 WHEN 'LISTED' THEN 1 WHEN 'DELISTED' THEN 1 ELSE 0 END = 1),
  CONSTRAINT chk_stock_corporate_action_delisting_treatment CHECK (delisting_treatment IS NULL OR delisting_treatment = 'ZERO_VALUE'),
  CONSTRAINT chk_stock_corporate_action_offering_type CHECK (offering_type IS NULL OR CASE `offering_type` WHEN 'SHAREHOLDER_ALLOCATION' THEN 1 WHEN 'PUBLIC_OFFERING' THEN 1 ELSE 0 END = 1),
  CONSTRAINT chk_stock_corporate_action_share_quantity CHECK (share_quantity IS NULL OR share_quantity > 0),
  CONSTRAINT chk_stock_corporate_action_issue_price CHECK (issue_price IS NULL OR issue_price > 0),
  CONSTRAINT chk_stock_corporate_action_dividend_amount CHECK (dividend_amount IS NULL OR dividend_amount > 0),
  CONSTRAINT chk_stock_corporate_action_base_price CHECK (base_price IS NULL OR base_price > 0),
  CONSTRAINT chk_stock_corporate_action_ex_rights_price CHECK (theoretical_ex_rights_price IS NULL OR theoretical_ex_rights_price > 0),
  CONSTRAINT chk_stock_corporate_action_paid_dates CHECK (ex_rights_date IS NULL OR payment_date IS NULL OR payment_date >= ex_rights_date),
  CONSTRAINT chk_stock_corporate_action_listing_dates CHECK (payment_date IS NULL OR listing_date IS NULL OR listing_date >= payment_date),
  CONSTRAINT chk_stock_corporate_action_subscription_dates CHECK (subscription_start_date IS NULL OR subscription_end_date IS NULL OR subscription_end_date >= subscription_start_date),
  CONSTRAINT chk_stock_corporate_action_paid_date_order CHECK (
    action_type <> 'PAID_IN_CAPITAL_INCREASE'
    OR (
      subscription_end_date >= subscription_start_date
      AND payment_date > subscription_end_date
      AND listing_date > payment_date
      AND (
        offering_type <> 'SHAREHOLDER_ALLOCATION'
        OR (record_date > ex_rights_date AND subscription_start_date >= record_date)
      )
    )
  ),
  CONSTRAINT chk_stock_corporate_action_split_from CHECK (split_from IS NULL OR split_from > 0),
  CONSTRAINT chk_stock_corporate_action_split_to CHECK (split_to IS NULL OR split_to > 0),
  CONSTRAINT chk_stock_corporate_action_issue_required CHECK (
    action_type NOT IN ('INITIAL_ISSUE', 'PAID_IN_CAPITAL_INCREASE')
    OR (share_quantity IS NOT NULL AND issue_price IS NOT NULL)
  ),
  CONSTRAINT chk_stock_corporate_action_paid_schedule_required CHECK (
    action_type <> 'PAID_IN_CAPITAL_INCREASE'
    OR (
      offering_type IS NOT NULL
      AND subscription_start_date IS NOT NULL
      AND subscription_end_date IS NOT NULL
      AND payment_date IS NOT NULL
      AND listing_date IS NOT NULL
      AND (
        (
          offering_type = 'SHAREHOLDER_ALLOCATION'
          AND base_price IS NOT NULL
          AND theoretical_ex_rights_price IS NOT NULL
          AND ex_rights_date IS NOT NULL
          AND record_date IS NOT NULL
        )
        OR (
          offering_type = 'PUBLIC_OFFERING'
          AND ex_rights_date IS NULL
          AND record_date IS NULL
          AND theoretical_ex_rights_price IS NULL
        )
      )
    )
  ),
  CONSTRAINT chk_stock_corporate_action_split_required CHECK (
    action_type <> 'STOCK_SPLIT'
    OR (
      split_from IS NOT NULL
      AND split_to IS NOT NULL
      AND split_to > split_from
      AND MOD(split_to, split_from) = 0
    )
  ),
  CONSTRAINT chk_stock_corporate_action_dividend_required CHECK (
    action_type <> 'CASH_DIVIDEND'
    OR (
      dividend_amount IS NOT NULL
      AND base_price IS NOT NULL
      AND theoretical_ex_rights_price IS NOT NULL
      AND ex_rights_date IS NOT NULL
      AND payment_date IS NOT NULL
    )
  ),
  CONSTRAINT chk_stock_corporate_action_free_share_required CHECK (
    action_type NOT IN ('BONUS_ISSUE', 'STOCK_DIVIDEND')
    OR (
      share_quantity IS NOT NULL
      AND base_price IS NOT NULL
      AND theoretical_ex_rights_price IS NOT NULL
      AND ex_rights_date IS NOT NULL
      AND listing_date IS NOT NULL
    )
  ),
  CONSTRAINT chk_stock_corporate_action_delisting_required CHECK (
    action_type <> 'DELISTING'
    OR (
      delisting_date IS NOT NULL
      AND delisting_treatment = 'ZERO_VALUE'
    )
  ),
  CONSTRAINT chk_stock_corporate_action_field_scope CHECK (
    (action_type IN ('INITIAL_ISSUE', 'PAID_IN_CAPITAL_INCREASE', 'BONUS_ISSUE', 'STOCK_DIVIDEND') OR share_quantity IS NULL)
    AND (action_type IN ('INITIAL_ISSUE', 'PAID_IN_CAPITAL_INCREASE') OR issue_price IS NULL)
    AND (action_type = 'PAID_IN_CAPITAL_INCREASE' OR offering_type IS NULL)
    AND (action_type = 'PAID_IN_CAPITAL_INCREASE' OR subscription_start_date IS NULL)
    AND (action_type = 'PAID_IN_CAPITAL_INCREASE' OR subscription_end_date IS NULL)
    AND (action_type = 'CASH_DIVIDEND' OR dividend_amount IS NULL)
    AND (action_type IN ('PAID_IN_CAPITAL_INCREASE', 'CASH_DIVIDEND', 'BONUS_ISSUE', 'STOCK_DIVIDEND') OR base_price IS NULL)
    AND (action_type IN ('PAID_IN_CAPITAL_INCREASE', 'CASH_DIVIDEND', 'BONUS_ISSUE', 'STOCK_DIVIDEND') OR theoretical_ex_rights_price IS NULL)
    AND (action_type IN ('PAID_IN_CAPITAL_INCREASE', 'CASH_DIVIDEND', 'BONUS_ISSUE', 'STOCK_DIVIDEND') OR ex_rights_date IS NULL)
    AND (action_type = 'PAID_IN_CAPITAL_INCREASE' OR record_date IS NULL)
    AND (action_type IN ('PAID_IN_CAPITAL_INCREASE', 'CASH_DIVIDEND', 'BONUS_ISSUE', 'STOCK_DIVIDEND') OR entitlement_close_cycle_id IS NULL)
    AND (action_type IN ('PAID_IN_CAPITAL_INCREASE', 'CASH_DIVIDEND', 'BONUS_ISSUE', 'STOCK_DIVIDEND') OR entitlement_close_run_id IS NULL)
    AND (action_type IN ('PAID_IN_CAPITAL_INCREASE', 'CASH_DIVIDEND') OR payment_date IS NULL)
    AND (action_type IN ('PAID_IN_CAPITAL_INCREASE', 'STOCK_SPLIT', 'BONUS_ISSUE', 'STOCK_DIVIDEND') OR listing_date IS NULL)
    AND (action_type = 'DELISTING' OR delisting_date IS NULL)
    AND (action_type = 'DELISTING' OR delisting_treatment IS NULL)
    AND (action_type = 'STOCK_SPLIT' OR (split_from IS NULL AND split_to IS NULL))
  ),
  CONSTRAINT chk_stock_corporate_action_entitlement_close_pair CHECK (
    (entitlement_close_cycle_id IS NULL AND entitlement_close_run_id IS NULL)
    OR (entitlement_close_cycle_id IS NOT NULL AND entitlement_close_run_id IS NOT NULL)
  ),
  CONSTRAINT chk_stock_corporate_action_initial_listed CHECK (
    action_type <> 'INITIAL_ISSUE'
    OR (
      status = 'LISTED'
      AND listed_at IS NOT NULL
      AND applied_at IS NULL
      AND paid_at IS NULL
    )
  )
);

CREATE INDEX IF NOT EXISTS idx_stock_corporate_action_symbol_created ON stock_corporate_action(symbol, created_at);
CREATE INDEX IF NOT EXISTS idx_stock_corporate_action_created ON stock_corporate_action(created_at, id);
CREATE INDEX IF NOT EXISTS idx_stock_corporate_action_type_created ON stock_corporate_action(action_type, created_at, id);
CREATE INDEX IF NOT EXISTS idx_stock_corporate_action_status_dates ON stock_corporate_action(status, ex_rights_date, payment_date, listing_date, delisting_date);
CREATE INDEX IF NOT EXISTS idx_stock_corporate_action_status_symbol ON stock_corporate_action(status, symbol);
CREATE INDEX IF NOT EXISTS idx_stock_corporate_action_entitlement_close ON stock_corporate_action(entitlement_close_cycle_id, entitlement_close_run_id);

CREATE TABLE IF NOT EXISTS stock_corporate_action_entitlement (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action_id BIGINT NOT NULL,
  account_id BIGINT NOT NULL,
  symbol VARCHAR(20) NOT NULL,
  quantity BIGINT NOT NULL,
  share_quantity BIGINT,
  cash_amount DECIMAL(19,2),
  subscribed_share_quantity BIGINT,
  subscribed_cash_amount DECIMAL(19,2),
  forfeited_share_quantity BIGINT NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'ANNOUNCED',
  holding_snapshot_run_id BIGINT,
  created_at TIMESTAMP NOT NULL,
  subscribed_at TIMESTAMP,
  paid_at TIMESTAMP,
  CONSTRAINT uk_stock_corporate_action_entitlement_action_account UNIQUE (action_id, account_id),
  CONSTRAINT chk_stock_corporate_action_entitlement_quantity CHECK (quantity > 0),
  CONSTRAINT chk_stock_corporate_action_entitlement_share CHECK (share_quantity IS NULL OR share_quantity > 0),
  CONSTRAINT chk_stock_corporate_action_entitlement_cash CHECK (cash_amount IS NULL OR cash_amount > 0),
  CONSTRAINT chk_stock_corporate_action_entitlement_subscribed_share CHECK (subscribed_share_quantity IS NULL OR subscribed_share_quantity > 0),
  CONSTRAINT chk_stock_corporate_action_entitlement_subscribed_share_limit CHECK (
    subscribed_share_quantity IS NULL
    OR share_quantity IS NULL
    OR subscribed_share_quantity <= share_quantity
  ),
  CONSTRAINT chk_stock_corporate_action_entitlement_subscribed_cash CHECK (subscribed_cash_amount IS NULL OR subscribed_cash_amount > 0),
  CONSTRAINT chk_stock_corporate_action_entitlement_forfeited_share CHECK (forfeited_share_quantity >= 0),
  CONSTRAINT chk_stock_corporate_action_entitlement_finalized_share_limit CHECK (
    (
      share_quantity IS NULL
      OR coalesce(subscribed_share_quantity, 0) + forfeited_share_quantity <= share_quantity
    )
    AND (
      status NOT IN ('SUBSCRIBED', 'PAID')
      OR subscribed_at IS NULL
      OR share_quantity IS NULL
      OR coalesce(subscribed_share_quantity, 0) + forfeited_share_quantity = share_quantity
    )
    AND (
      status <> 'EXPIRED'
      OR share_quantity IS NULL
      OR coalesce(subscribed_share_quantity, 0) + forfeited_share_quantity = share_quantity
    )
  ),
  CONSTRAINT chk_stock_corporate_action_entitlement_subscription_complete CHECK (
    status NOT IN ('PARTIALLY_SUBSCRIBED', 'SUBSCRIBED')
    OR (subscribed_share_quantity IS NOT NULL AND subscribed_cash_amount IS NOT NULL AND subscribed_at IS NOT NULL)
  ),
  CONSTRAINT chk_stock_corporate_action_entitlement_value CHECK (cash_amount IS NOT NULL OR share_quantity IS NOT NULL),
  CONSTRAINT chk_stock_corporate_action_entitlement_status CHECK (CASE `status` WHEN 'ANNOUNCED' THEN 1 WHEN 'PARTIALLY_SUBSCRIBED' THEN 1 WHEN 'SUBSCRIBED' THEN 1 WHEN 'EXPIRED' THEN 1 WHEN 'PAID' THEN 1 ELSE 0 END = 1)
);

CREATE INDEX IF NOT EXISTS idx_stock_corporate_action_entitlement_account_created ON stock_corporate_action_entitlement(account_id, created_at);
CREATE INDEX IF NOT EXISTS idx_stock_corporate_action_entitlement_account_status ON stock_corporate_action_entitlement(account_id, status);
CREATE INDEX IF NOT EXISTS idx_stock_corporate_action_entitlement_status ON stock_corporate_action_entitlement(status, action_id);
CREATE INDEX IF NOT EXISTS idx_stock_corporate_action_entitlement_action_status_id ON stock_corporate_action_entitlement(action_id, status, id);
CREATE INDEX IF NOT EXISTS idx_stock_corporate_action_entitlement_snapshot_run ON stock_corporate_action_entitlement(holding_snapshot_run_id);

CREATE TABLE IF NOT EXISTS stock_corporate_action_processing (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action_id BIGINT NOT NULL,
  account_scope_key VARCHAR(40) NOT NULL DEFAULT 'ALL',
  action_phase VARCHAR(80) NOT NULL,
  effective_business_date DATE NOT NULL,
  status VARCHAR(20) NOT NULL,
  attempt_count INT NOT NULL DEFAULT 1,
  processed_count INT NOT NULL DEFAULT 0,
  amount DECIMAL(19,2),
  quantity BIGINT,
  ledger_reference_id VARCHAR(100),
  processed_at TIMESTAMP,
  last_error VARCHAR(1000),
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  CONSTRAINT uk_stock_corporate_action_processing_unit UNIQUE (
    action_id, account_scope_key, action_phase, effective_business_date
  ),
  CONSTRAINT chk_stock_corporate_action_processing_scope CHECK (account_scope_key <> ''),
  CONSTRAINT chk_stock_corporate_action_processing_status CHECK (
    CASE `status` WHEN 'PENDING' THEN 1 WHEN 'COMPLETED' THEN 1 WHEN 'FAILED' THEN 1 ELSE 0 END = 1
  ),
  CONSTRAINT chk_stock_corporate_action_processing_attempt CHECK (attempt_count > 0),
  CONSTRAINT chk_stock_corporate_action_processing_count CHECK (processed_count >= 0),
  CONSTRAINT chk_stock_corporate_action_processing_amount CHECK (amount IS NULL OR amount >= 0),
  CONSTRAINT chk_stock_corporate_action_processing_quantity CHECK (quantity IS NULL OR quantity >= 0)
);

CREATE INDEX IF NOT EXISTS idx_stock_corporate_action_processing_status_date
  ON stock_corporate_action_processing(status, effective_business_date, action_phase, action_id);

CREATE TABLE IF NOT EXISTS stock_price (
  symbol VARCHAR(20) NOT NULL PRIMARY KEY,
  current_price DECIMAL(19,2) NOT NULL,
  previous_close DECIMAL(19,2) NOT NULL,
  price_time TIMESTAMP NOT NULL,
  provider VARCHAR(40) NOT NULL,
  CONSTRAINT chk_stock_price_current_non_negative CHECK (current_price >= 0),
  CONSTRAINT chk_stock_price_previous_close_non_negative CHECK (previous_close >= 0)
);

CREATE TABLE IF NOT EXISTS stock_price_tick (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  symbol VARCHAR(20) NOT NULL,
  price DECIMAL(19,2) NOT NULL,
  provider VARCHAR(40) NOT NULL,
  price_time TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL,
  CONSTRAINT chk_stock_price_tick_price_non_negative CHECK (price >= 0)
);

CREATE INDEX IF NOT EXISTS idx_stock_price_tick_symbol_time_id ON stock_price_tick(symbol, price_time, id);

CREATE TABLE IF NOT EXISTS stock_order (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_order_id VARCHAR(64) NOT NULL UNIQUE,
  account_id BIGINT NOT NULL,
  symbol VARCHAR(20) NOT NULL,
  market_type VARCHAR(30) NOT NULL DEFAULT 'ORDER_BOOK',
  side VARCHAR(10) NOT NULL,
  order_type VARCHAR(10) NOT NULL,
  status VARCHAR(20) NOT NULL,
  limit_price DECIMAL(19,2),
  quantity BIGINT NOT NULL,
  filled_quantity BIGINT NOT NULL,
  average_fill_price DECIMAL(19,2),
  reserved_cash DECIMAL(19,2) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  CONSTRAINT chk_stock_order_market_type_valid CHECK (CASE `market_type` WHEN 'VIRTUAL_PRICE' THEN 1 WHEN 'ORDER_BOOK' THEN 1 ELSE 0 END = 1),
  CONSTRAINT chk_stock_order_side_valid CHECK (CASE `side` WHEN 'BUY' THEN 1 WHEN 'SELL' THEN 1 ELSE 0 END = 1),
  CONSTRAINT chk_stock_order_type_valid CHECK (CASE `order_type` WHEN 'LIMIT' THEN 1 WHEN 'MARKET' THEN 1 ELSE 0 END = 1),
  CONSTRAINT chk_stock_order_status_valid CHECK (CASE `status` WHEN 'PENDING' THEN 1 WHEN 'PARTIALLY_FILLED' THEN 1 WHEN 'FILLED' THEN 1 WHEN 'CANCELLED' THEN 1 WHEN 'REJECTED' THEN 1 ELSE 0 END = 1),
  CONSTRAINT chk_stock_order_limit_price_positive CHECK (limit_price IS NULL OR limit_price > 0),
  CONSTRAINT chk_stock_order_quantity_positive CHECK (quantity > 0),
  CONSTRAINT chk_stock_order_filled_quantity_valid CHECK (filled_quantity >= 0 AND filled_quantity <= quantity),
  CONSTRAINT chk_stock_order_average_fill_price_positive CHECK (average_fill_price IS NULL OR average_fill_price > 0),
  CONSTRAINT chk_stock_order_reserved_cash_non_negative CHECK (reserved_cash >= 0),
  CONSTRAINT chk_stock_order_terminal_reserved_cash_zero CHECK ((status <> 'FILLED' AND status <> 'CANCELLED' AND status <> 'REJECTED') OR reserved_cash = 0)
);

CREATE INDEX IF NOT EXISTS idx_stock_order_account_created ON stock_order(account_id, created_at);
CREATE INDEX IF NOT EXISTS idx_stock_order_account_market_created ON stock_order(account_id, market_type, created_at);
CREATE INDEX IF NOT EXISTS idx_stock_order_account_status_created ON stock_order(account_id, status, created_at);
CREATE INDEX IF NOT EXISTS idx_stock_order_account_symbol_created ON stock_order(account_id, symbol, created_at);
CREATE INDEX IF NOT EXISTS idx_stock_order_market_status_symbol ON stock_order(market_type, status, symbol);
CREATE INDEX IF NOT EXISTS idx_stock_order_market_status_side ON stock_order(market_type, status, side);
CREATE INDEX IF NOT EXISTS idx_stock_order_market_status_account_time ON stock_order(market_type, status, account_id, created_at);
CREATE INDEX IF NOT EXISTS idx_stock_order_market_account_time ON stock_order(market_type, account_id, created_at);
CREATE INDEX IF NOT EXISTS idx_stock_order_market_account_symbol_time ON stock_order(market_type, account_id, symbol, created_at);
CREATE INDEX IF NOT EXISTS idx_stock_order_market_created_status ON stock_order(market_type, created_at, status);
CREATE INDEX IF NOT EXISTS idx_stock_order_side_status_account ON stock_order(side, status, account_id);
CREATE INDEX IF NOT EXISTS idx_stock_order_execution_scan ON stock_order(status, order_type, created_at, symbol);
CREATE INDEX IF NOT EXISTS idx_stock_order_order_book_match ON stock_order(market_type, symbol, side, status, order_type, limit_price, created_at, id);
CREATE INDEX IF NOT EXISTS idx_stock_order_order_book_expiry ON stock_order(market_type, symbol, created_at, id, status, account_id);

CREATE TABLE IF NOT EXISTS stock_execution (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL,
  account_id BIGINT NOT NULL,
  symbol VARCHAR(20) NOT NULL,
  side VARCHAR(10) NOT NULL,
  quantity BIGINT NOT NULL,
  price DECIMAL(19,2) NOT NULL,
  gross_amount DECIMAL(19,2) NOT NULL,
  fee_amount DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  tax_amount DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  net_amount DECIMAL(19,2) NOT NULL,
  realized_profit DECIMAL(19,2),
  source VARCHAR(30) NOT NULL,
  executed_at TIMESTAMP NOT NULL,
  CONSTRAINT chk_stock_execution_side_valid CHECK (CASE `side` WHEN 'BUY' THEN 1 WHEN 'SELL' THEN 1 ELSE 0 END = 1),
  CONSTRAINT chk_stock_execution_source_valid CHECK (CASE `source` WHEN 'VIRTUAL_MARKET_PRICE' THEN 1 WHEN 'INTERNAL_ORDER_BOOK' THEN 1 ELSE 0 END = 1),
  CONSTRAINT chk_stock_execution_quantity_positive CHECK (quantity > 0),
  CONSTRAINT chk_stock_execution_price_positive CHECK (price > 0),
  CONSTRAINT chk_stock_execution_gross_non_negative CHECK (gross_amount >= 0),
  CONSTRAINT chk_stock_execution_fee_non_negative CHECK (fee_amount >= 0),
  CONSTRAINT chk_stock_execution_tax_non_negative CHECK (tax_amount >= 0),
  CONSTRAINT chk_stock_execution_net_non_negative CHECK (net_amount >= 0)
);

CREATE INDEX IF NOT EXISTS idx_stock_execution_account_time ON stock_execution(account_id, executed_at);
CREATE INDEX IF NOT EXISTS idx_stock_execution_account_source_time ON stock_execution(account_id, source, executed_at);
CREATE INDEX IF NOT EXISTS idx_stock_execution_account_symbol_time ON stock_execution(account_id, symbol, executed_at);
CREATE INDEX IF NOT EXISTS idx_stock_execution_time_account ON stock_execution(executed_at, account_id);
CREATE INDEX IF NOT EXISTS idx_stock_execution_source_account_time ON stock_execution(source, account_id, executed_at);
CREATE INDEX IF NOT EXISTS idx_stock_execution_source_account_symbol_time ON stock_execution(source, account_id, symbol, executed_at);
CREATE INDEX IF NOT EXISTS idx_stock_execution_source_time_account ON stock_execution(source, executed_at, account_id);
CREATE INDEX IF NOT EXISTS idx_stock_execution_source_symbol_time ON stock_execution(source, symbol, executed_at);
CREATE INDEX IF NOT EXISTS idx_stock_execution_candle ON stock_execution(source, symbol, side, executed_at, id, price, quantity, gross_amount);
CREATE INDEX IF NOT EXISTS idx_stock_execution_source_time ON stock_execution(source, executed_at);
CREATE INDEX IF NOT EXISTS idx_stock_execution_order ON stock_execution(order_id);

CREATE TABLE IF NOT EXISTS stock_holding (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id BIGINT NOT NULL,
  symbol VARCHAR(20) NOT NULL,
  quantity BIGINT NOT NULL,
  reserved_quantity BIGINT NOT NULL DEFAULT 0,
  average_price DECIMAL(19,2) NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  CONSTRAINT uk_stock_holding_account_symbol UNIQUE (account_id, symbol),
  CONSTRAINT chk_stock_holding_quantity_non_negative CHECK (quantity >= 0),
  CONSTRAINT chk_stock_holding_reserved_quantity_valid CHECK (reserved_quantity >= 0 AND reserved_quantity <= quantity),
  CONSTRAINT chk_stock_holding_average_price_positive CHECK (average_price > 0)
);

CREATE INDEX IF NOT EXISTS idx_stock_holding_symbol_account ON stock_holding(symbol, account_id);
CREATE INDEX IF NOT EXISTS idx_stock_holding_empty_cleanup ON stock_holding(quantity, reserved_quantity, updated_at);

CREATE TABLE IF NOT EXISTS stock_post_close_cycle (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_date DATE NOT NULL,
  scope_type VARCHAR(20) NOT NULL,
  scope_key VARCHAR(40) NOT NULL,
  cycle_kind VARCHAR(20) NOT NULL DEFAULT 'TRADING',
  skip_reason VARCHAR(500),
  phase VARCHAR(60) NOT NULL DEFAULT 'OPEN',
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  phase_revision INT NOT NULL DEFAULT 1,
  version BIGINT NOT NULL DEFAULT 0,
  owner_id VARCHAR(128),
  lease_until TIMESTAMP,
  next_retry_at TIMESTAMP,
  close_run_id BIGINT,
  settlement_eligible_at TIMESTAMP,
  attempt_count INT NOT NULL DEFAULT 0,
  started_at TIMESTAMP,
  completed_at TIMESTAMP,
  last_error_code VARCHAR(80),
  last_error_message VARCHAR(1000),
  build_version VARCHAR(100),
  schema_version VARCHAR(100),
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  CONSTRAINT uk_stock_post_close_cycle_scope UNIQUE (business_date, scope_type, scope_key),
  CONSTRAINT chk_stock_post_close_cycle_scope_type CHECK (
    CASE `scope_type` WHEN 'FULL_MARKET' THEN 1 WHEN 'SYMBOL' THEN 1 ELSE 0 END = 1
  ),
  CONSTRAINT chk_stock_post_close_cycle_scope_key CHECK (scope_key <> ''),
  CONSTRAINT chk_stock_post_close_cycle_kind CHECK (
    CASE `cycle_kind` WHEN 'TRADING' THEN 1 WHEN 'SKIPPED' THEN 1 ELSE 0 END = 1
  ),
  CONSTRAINT chk_stock_post_close_cycle_skip_reason CHECK (
    cycle_kind <> 'SKIPPED' OR skip_reason IS NOT NULL
  ),
  CONSTRAINT chk_stock_post_close_cycle_phase CHECK (
    CASE `phase`
      WHEN 'OPEN' THEN 1 WHEN 'CLOSE_REQUESTED' THEN 1 WHEN 'ORDER_ENTRY_CLOSED' THEN 1
      WHEN 'EXECUTION_DRAINED' THEN 1 WHEN 'LEDGER_FROZEN' THEN 1 WHEN 'PORTFOLIO_SETTLED' THEN 1
      WHEN 'OVERNIGHT_CASH_APPLIED' THEN 1 WHEN 'CORPORATE_CASH_APPLIED' THEN 1
      WHEN 'REPORTS_AGGREGATED' THEN 1 WHEN 'PREOPEN_SECURITY_TRANSFORMS_APPLIED' THEN 1
      WHEN 'MARKET_DATA_PREPARED' THEN 1 WHEN 'AUTO_MARKET_PREPARED' THEN 1
      WHEN 'READY_TO_OPEN' THEN 1 WHEN 'COMPLETED' THEN 1 ELSE 0
    END = 1
  ),
  CONSTRAINT chk_stock_post_close_cycle_status CHECK (
    CASE `status` WHEN 'PENDING' THEN 1 WHEN 'RUNNING' THEN 1 WHEN 'DEFERRED' THEN 1 WHEN 'FAILED' THEN 1 WHEN 'COMPLETED' THEN 1 ELSE 0 END = 1
  ),
  CONSTRAINT chk_stock_post_close_cycle_revision CHECK (phase_revision > 0),
  CONSTRAINT chk_stock_post_close_cycle_version CHECK (version >= 0),
  CONSTRAINT chk_stock_post_close_cycle_attempt_count CHECK (attempt_count >= 0)
);

CREATE INDEX IF NOT EXISTS idx_stock_post_close_cycle_phase_status
  ON stock_post_close_cycle(phase, status, business_date, id);
CREATE INDEX IF NOT EXISTS idx_stock_post_close_cycle_scope_date_status
  ON stock_post_close_cycle(scope_type, scope_key, business_date, status, id);
CREATE INDEX IF NOT EXISTS idx_stock_post_close_cycle_scope_status_date
  ON stock_post_close_cycle(scope_type, scope_key, status, business_date, id);
CREATE INDEX IF NOT EXISTS idx_stock_post_close_cycle_lease
  ON stock_post_close_cycle(status, lease_until, business_date, id);
CREATE INDEX IF NOT EXISTS idx_stock_post_close_cycle_close_run
  ON stock_post_close_cycle(close_run_id);

CREATE TABLE IF NOT EXISTS stock_post_close_phase_attempt (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cycle_id BIGINT NOT NULL,
  phase VARCHAR(60) NOT NULL,
  attempt_no INT NOT NULL,
  batch_job_execution_id BIGINT,
  owner_id VARCHAR(128) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'RUNNING',
  started_at TIMESTAMP NOT NULL,
  completed_at TIMESTAMP,
  error_code VARCHAR(80),
  error_message VARCHAR(1000),
  build_version VARCHAR(100),
  schema_version VARCHAR(100),
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  CONSTRAINT uk_stock_post_close_phase_attempt UNIQUE (cycle_id, phase, attempt_no),
  CONSTRAINT chk_stock_post_close_phase_attempt_no CHECK (attempt_no > 0),
  CONSTRAINT chk_stock_post_close_phase_attempt_owner CHECK (owner_id <> ''),
  CONSTRAINT chk_stock_post_close_phase_attempt_status CHECK (
    CASE `status` WHEN 'RUNNING' THEN 1 WHEN 'COMPLETED' THEN 1 WHEN 'FAILED' THEN 1 WHEN 'ABANDONED' THEN 1 ELSE 0 END = 1
  )
);

CREATE INDEX IF NOT EXISTS idx_stock_post_close_phase_attempt_status
  ON stock_post_close_phase_attempt(status, started_at, id);
CREATE INDEX IF NOT EXISTS idx_stock_post_close_phase_attempt_cycle_id
  ON stock_post_close_phase_attempt(cycle_id, id);
CREATE INDEX IF NOT EXISTS idx_stock_post_close_phase_attempt_job
  ON stock_post_close_phase_attempt(batch_job_execution_id);

CREATE TABLE IF NOT EXISTS stock_post_close_readiness_check (
  close_cycle_id BIGINT NOT NULL,
  check_code VARCHAR(60) NOT NULL,
  display_order INT NOT NULL,
  check_status VARCHAR(20) NOT NULL,
  failure_count BIGINT NOT NULL DEFAULT 0,
  message VARCHAR(500),
  checked_at TIMESTAMP NOT NULL,
  PRIMARY KEY (close_cycle_id, check_code),
  CONSTRAINT uk_stock_post_close_readiness_order UNIQUE (close_cycle_id, display_order),
  CONSTRAINT chk_stock_post_close_readiness_order CHECK (display_order > 0),
  CONSTRAINT chk_stock_post_close_readiness_status CHECK (
    CASE `check_status` WHEN 'PASSED' THEN 1 WHEN 'FAILED' THEN 1 ELSE 0 END = 1
  ),
  CONSTRAINT chk_stock_post_close_readiness_failure_count CHECK (failure_count >= 0)
);

CREATE TABLE IF NOT EXISTS stock_post_close_cycle_metric (
  close_cycle_id BIGINT NOT NULL PRIMARY KEY,
  close_run_id BIGINT,
  captured_open_order_count BIGINT NOT NULL DEFAULT 0,
  cancelled_order_count BIGINT NOT NULL DEFAULT 0,
  released_buy_cash DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  released_sell_quantity BIGINT NOT NULL DEFAULT 0,
  settlement_target_account_count BIGINT NOT NULL DEFAULT 0,
  account_snapshot_count BIGINT NOT NULL DEFAULT 0,
  holding_snapshot_count BIGINT NOT NULL DEFAULT 0,
  price_snapshot_count BIGINT NOT NULL DEFAULT 0,
  open_order_summary_count BIGINT NOT NULL DEFAULT 0,
  reconciliation_mismatch_count BIGINT NOT NULL DEFAULT 0,
  settled_account_count BIGINT NOT NULL DEFAULT 0,
  settlement_missing_account_count BIGINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL,
  CONSTRAINT chk_stock_post_close_cycle_metric_counts CHECK (
    captured_open_order_count >= 0
    AND cancelled_order_count >= 0
    AND settlement_target_account_count >= 0
    AND account_snapshot_count >= 0
    AND holding_snapshot_count >= 0
    AND price_snapshot_count >= 0
    AND open_order_summary_count >= 0
    AND reconciliation_mismatch_count >= 0
    AND settled_account_count >= 0
    AND settlement_missing_account_count >= 0
  ),
  CONSTRAINT chk_stock_post_close_cycle_metric_releases CHECK (
    released_buy_cash >= 0
    AND released_sell_quantity >= 0
  )
);
CREATE INDEX IF NOT EXISTS idx_stock_post_close_cycle_metric_run
  ON stock_post_close_cycle_metric(close_run_id);

CREATE TABLE IF NOT EXISTS stock_market_close_run (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  symbol VARCHAR(20),
  business_date DATE NOT NULL,
  closed_at TIMESTAMP NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'COMPLETED',
  cancelled_order_count INT NOT NULL DEFAULT 0,
  holding_snapshot_count INT NOT NULL DEFAULT 0,
  price_rollover_count INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL,
  completed_at TIMESTAMP,
  CONSTRAINT chk_stock_market_close_run_status CHECK (CASE `status` WHEN 'STARTED' THEN 1 WHEN 'COMPLETED' THEN 1 WHEN 'FAILED' THEN 1 ELSE 0 END = 1),
  CONSTRAINT chk_stock_market_close_run_cancelled_non_negative CHECK (cancelled_order_count >= 0),
  CONSTRAINT chk_stock_market_close_run_snapshot_non_negative CHECK (holding_snapshot_count >= 0),
  CONSTRAINT chk_stock_market_close_run_price_non_negative CHECK (price_rollover_count >= 0)
);

CREATE INDEX IF NOT EXISTS idx_stock_market_close_run_symbol_time ON stock_market_close_run(symbol, closed_at, id);
CREATE INDEX IF NOT EXISTS idx_stock_market_close_run_date_time ON stock_market_close_run(business_date, closed_at, id);

CREATE TABLE IF NOT EXISTS stock_holding_snapshot (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  close_cycle_id BIGINT NULL,
  close_run_id BIGINT NOT NULL,
  account_id BIGINT NOT NULL,
  symbol VARCHAR(20) NOT NULL,
  quantity BIGINT NOT NULL,
  reserved_quantity BIGINT NOT NULL DEFAULT 0,
  average_price DECIMAL(19,2) NOT NULL,
  evaluation_price DECIMAL(19,2) NULL,
  snapshot_at TIMESTAMP NOT NULL,
  CONSTRAINT uk_stock_holding_snapshot_run_account_symbol UNIQUE (close_run_id, account_id, symbol),
  CONSTRAINT chk_stock_holding_snapshot_quantity_non_negative CHECK (quantity >= 0),
  CONSTRAINT chk_stock_holding_snapshot_reserved_valid CHECK (reserved_quantity >= 0 AND reserved_quantity <= quantity),
  CONSTRAINT chk_stock_holding_snapshot_average_price_positive CHECK (average_price > 0),
  CONSTRAINT chk_stock_holding_snapshot_evaluation_price CHECK (evaluation_price IS NULL OR evaluation_price >= 0)
);

CREATE INDEX IF NOT EXISTS idx_stock_holding_snapshot_cycle_account ON stock_holding_snapshot(close_cycle_id, account_id, symbol);
CREATE INDEX IF NOT EXISTS idx_stock_holding_snapshot_symbol_run ON stock_holding_snapshot(symbol, close_run_id, account_id);
CREATE INDEX IF NOT EXISTS idx_stock_holding_snapshot_account_time ON stock_holding_snapshot(account_id, snapshot_at, id);

CREATE TABLE IF NOT EXISTS stock_close_account_snapshot (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  close_cycle_id BIGINT NOT NULL,
  close_run_id BIGINT NOT NULL,
  account_id BIGINT NOT NULL,
  user_key VARCHAR(64) NULL,
  account_status VARCHAR(20) NOT NULL,
  participant_category VARCHAR(30) NOT NULL DEFAULT 'MANUAL_PARTICIPANT',
  settlement_target BOOLEAN NOT NULL,
  pre_cancel_cash DECIMAL(19,2) NOT NULL,
  pre_cancel_order_reserved_cash DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  subscription_reserved_cash DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  post_cancel_cash DECIMAL(19,2) NULL,
  external_net_cash_flow DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  cash_flow_watermark_id BIGINT NOT NULL DEFAULT 0,
  holding_market_value DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  holding_quantity BIGINT NOT NULL DEFAULT 0,
  reserved_sell_quantity BIGINT NOT NULL DEFAULT 0,
  holding_position_count BIGINT NOT NULL DEFAULT 0,
  reconciliation_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  snapshot_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL,
  CONSTRAINT uk_stock_close_account_snapshot_cycle_account UNIQUE (close_cycle_id, account_id),
  CONSTRAINT chk_stock_close_account_snapshot_cash CHECK (
    pre_cancel_cash >= 0
    AND pre_cancel_order_reserved_cash >= 0
    AND subscription_reserved_cash >= 0
    AND (post_cancel_cash IS NULL OR post_cancel_cash >= 0)
  ),
  CONSTRAINT chk_stock_close_account_snapshot_watermark CHECK (cash_flow_watermark_id >= 0),
  CONSTRAINT chk_stock_close_account_snapshot_holding_summary CHECK (
    holding_market_value >= 0
    AND holding_quantity >= 0
    AND reserved_sell_quantity >= 0
    AND reserved_sell_quantity <= holding_quantity
    AND holding_position_count >= 0
  ),
  CONSTRAINT chk_stock_close_account_snapshot_reconciliation CHECK (
    reconciliation_status IN ('PENDING', 'MATCHED', 'MISMATCHED')
  ),
  CONSTRAINT chk_stock_close_account_snapshot_participant_category CHECK (
    participant_category IN ('MANUAL_PARTICIPANT', 'AUTO_PARTICIPANT', 'LISTING_UNDERWRITER')
  )
);
CREATE INDEX IF NOT EXISTS idx_stock_close_account_snapshot_run_target
  ON stock_close_account_snapshot(close_run_id, settlement_target, account_id);
CREATE INDEX IF NOT EXISTS idx_stock_close_account_snapshot_cycle_target
  ON stock_close_account_snapshot(close_cycle_id, settlement_target, account_id);
CREATE INDEX IF NOT EXISTS idx_stock_close_account_snapshot_cycle_reconciliation
  ON stock_close_account_snapshot(close_cycle_id, reconciliation_status, account_id);
CREATE INDEX IF NOT EXISTS idx_stock_close_account_snapshot_account_cycle
  ON stock_close_account_snapshot(account_id, close_cycle_id);

CREATE TABLE IF NOT EXISTS stock_close_price_snapshot (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  close_cycle_id BIGINT NOT NULL,
  close_run_id BIGINT NOT NULL,
  symbol VARCHAR(20) NOT NULL,
  close_price DECIMAL(19,2) NOT NULL,
  previous_close DECIMAL(19,2) NOT NULL,
  price_time TIMESTAMP NULL,
  price_provider VARCHAR(40) NULL,
  last_execution_id BIGINT NULL,
  order_book_symbol BOOLEAN NOT NULL,
  snapshot_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL,
  CONSTRAINT uk_stock_close_price_snapshot_cycle_symbol UNIQUE (close_cycle_id, symbol),
  CONSTRAINT chk_stock_close_price_snapshot_price CHECK (close_price >= 0 AND previous_close >= 0),
  CONSTRAINT chk_stock_close_price_snapshot_execution CHECK (last_execution_id IS NULL OR last_execution_id > 0)
);
CREATE INDEX IF NOT EXISTS idx_stock_close_price_snapshot_run_symbol
  ON stock_close_price_snapshot(close_run_id, symbol);

CREATE TABLE IF NOT EXISTS stock_close_open_order_summary (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  close_cycle_id BIGINT NOT NULL,
  close_run_id BIGINT NOT NULL,
  symbol VARCHAR(20) NOT NULL,
  pre_cancel_open_order_count BIGINT NOT NULL DEFAULT 0,
  pre_cancel_buy_order_count BIGINT NOT NULL DEFAULT 0,
  pre_cancel_sell_order_count BIGINT NOT NULL DEFAULT 0,
  pre_cancel_remaining_buy_quantity BIGINT NOT NULL DEFAULT 0,
  pre_cancel_remaining_sell_quantity BIGINT NOT NULL DEFAULT 0,
  pre_cancel_reserved_buy_cash DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  pre_cancel_reserved_sell_quantity BIGINT NOT NULL DEFAULT 0,
  post_cancel_open_order_count BIGINT NOT NULL DEFAULT 0,
  reconciliation_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  snapshot_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL,
  CONSTRAINT uk_stock_close_open_order_summary_cycle_symbol UNIQUE (close_cycle_id, symbol),
  CONSTRAINT chk_stock_close_open_order_summary_counts CHECK (
    pre_cancel_open_order_count >= 0
    AND pre_cancel_buy_order_count >= 0
    AND pre_cancel_sell_order_count >= 0
    AND pre_cancel_remaining_buy_quantity >= 0
    AND pre_cancel_remaining_sell_quantity >= 0
    AND pre_cancel_reserved_buy_cash >= 0
    AND pre_cancel_reserved_sell_quantity >= 0
    AND post_cancel_open_order_count >= 0
  ),
  CONSTRAINT chk_stock_close_open_order_summary_reconciliation CHECK (
    reconciliation_status IN ('PENDING', 'MATCHED', 'MISMATCHED')
  )
);
CREATE INDEX IF NOT EXISTS idx_stock_close_open_order_summary_run
  ON stock_close_open_order_summary(close_run_id, symbol);

CREATE TABLE IF NOT EXISTS stock_close_open_order_snapshot (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  close_cycle_id BIGINT NOT NULL,
  close_run_id BIGINT NOT NULL,
  order_id BIGINT NOT NULL,
  account_id BIGINT NOT NULL,
  symbol VARCHAR(20) NOT NULL,
  side VARCHAR(10) NOT NULL,
  source_order_status VARCHAR(20) NOT NULL,
  remaining_quantity BIGINT NOT NULL,
  reserved_cash DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  captured_at TIMESTAMP NOT NULL,
  released_at TIMESTAMP NULL,
  CONSTRAINT uk_stock_close_open_order_snapshot_cycle_order UNIQUE (close_cycle_id, order_id),
  CONSTRAINT chk_stock_close_open_order_snapshot_side CHECK (side IN ('BUY', 'SELL')),
  CONSTRAINT chk_stock_close_open_order_snapshot_status CHECK (
    source_order_status IN ('PENDING', 'PARTIALLY_FILLED')
  ),
  CONSTRAINT chk_stock_close_open_order_snapshot_quantity CHECK (remaining_quantity > 0),
  CONSTRAINT chk_stock_close_open_order_snapshot_cash CHECK (reserved_cash >= 0)
);
CREATE INDEX IF NOT EXISTS idx_stock_close_open_order_snapshot_run_order
  ON stock_close_open_order_snapshot(close_run_id, order_id);
CREATE INDEX IF NOT EXISTS idx_stock_close_open_order_snapshot_cycle_release_order
  ON stock_close_open_order_snapshot(close_cycle_id, released_at, order_id);
CREATE INDEX IF NOT EXISTS idx_stock_close_open_order_snapshot_cycle_account
  ON stock_close_open_order_snapshot(close_cycle_id, account_id, side);
CREATE INDEX IF NOT EXISTS idx_stock_close_open_order_snapshot_cycle_holding
  ON stock_close_open_order_snapshot(close_cycle_id, symbol, account_id, side);
CREATE INDEX IF NOT EXISTS idx_stock_close_open_order_snapshot_cycle_stream
  ON stock_close_open_order_snapshot(close_cycle_id, symbol, source_order_status, order_id);

CREATE TABLE IF NOT EXISTS stock_order_book_daily_snapshot (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  close_run_id BIGINT NOT NULL,
  symbol VARCHAR(20) NOT NULL,
  simulation_trade_date DATE NOT NULL,
  snapshot_at TIMESTAMP NOT NULL,
  name VARCHAR(120) NOT NULL,
  market VARCHAR(20) NOT NULL,
  enabled BOOLEAN NOT NULL,
  market_enabled BOOLEAN NOT NULL,
  market_status VARCHAR(20) NOT NULL,
  issued_shares BIGINT NOT NULL,
  tradable_shares BIGINT NOT NULL,
  initial_price DECIMAL(19,2) NOT NULL,
  tick_size DECIMAL(19,2) NOT NULL,
  price_limit_rate DECIMAL(5,2) NOT NULL,
  close_price DECIMAL(19,2) NOT NULL,
  previous_close DECIMAL(19,2) NOT NULL,
  change_rate DECIMAL(9,4) NOT NULL DEFAULT 0.0000,
  price_time TIMESTAMP,
  price_provider VARCHAR(40),
  execution_count BIGINT NOT NULL DEFAULT 0,
  execution_quantity BIGINT NOT NULL DEFAULT 0,
  turnover_amount DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  open_price DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  high_price DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  low_price DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  last_execution_price DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  buy_quantity BIGINT NOT NULL DEFAULT 0,
  sell_quantity BIGINT NOT NULL DEFAULT 0,
  buy_net_amount DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  sell_net_amount DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  open_order_count BIGINT NOT NULL DEFAULT 0,
  open_buy_order_count BIGINT NOT NULL DEFAULT 0,
  open_sell_order_count BIGINT NOT NULL DEFAULT 0,
  reserved_buy_cash DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  holder_count BIGINT NOT NULL DEFAULT 0,
  holding_quantity BIGINT NOT NULL DEFAULT 0,
  pending_corporate_action_count BIGINT NOT NULL DEFAULT 0,
  first_executed_at TIMESTAMP,
  last_executed_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL,
  CONSTRAINT uk_stock_order_book_daily_snapshot_run_symbol UNIQUE (close_run_id, symbol),
  CONSTRAINT chk_stock_order_book_daily_snapshot_issued CHECK (issued_shares > 0),
  CONSTRAINT chk_stock_order_book_daily_snapshot_tradable CHECK (tradable_shares >= 0 AND tradable_shares <= issued_shares),
  CONSTRAINT chk_stock_order_book_daily_snapshot_price CHECK (close_price >= 0 AND previous_close >= 0 AND initial_price > 0 AND open_price >= 0 AND high_price >= 0 AND low_price >= 0 AND last_execution_price >= 0),
  CONSTRAINT chk_stock_order_book_daily_snapshot_flow CHECK (execution_count >= 0 AND execution_quantity >= 0 AND turnover_amount >= 0 AND buy_quantity >= 0 AND sell_quantity >= 0 AND buy_net_amount >= 0 AND sell_net_amount >= 0),
  CONSTRAINT chk_stock_order_book_daily_snapshot_open_order CHECK (open_order_count >= 0 AND open_buy_order_count >= 0 AND open_sell_order_count >= 0 AND reserved_buy_cash >= 0),
  CONSTRAINT chk_stock_order_book_daily_snapshot_holding CHECK (holder_count >= 0 AND holding_quantity >= 0 AND pending_corporate_action_count >= 0),
  CONSTRAINT chk_stock_order_book_daily_snapshot_tick CHECK (tick_size > 0),
  CONSTRAINT chk_stock_order_book_daily_snapshot_limit CHECK (price_limit_rate > 0 AND price_limit_rate <= 100)
);

CREATE INDEX IF NOT EXISTS idx_stock_order_book_daily_snapshot_date_symbol ON stock_order_book_daily_snapshot(simulation_trade_date, symbol, close_run_id);
CREATE INDEX IF NOT EXISTS idx_stock_order_book_daily_snapshot_symbol_date ON stock_order_book_daily_snapshot(symbol, simulation_trade_date, close_run_id);

CREATE TABLE IF NOT EXISTS stock_execution_daily_account_snapshot (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  close_run_id BIGINT NOT NULL,
  symbol VARCHAR(20) NOT NULL,
  simulation_trade_date DATE NOT NULL,
  account_id BIGINT NOT NULL,
  participant_category VARCHAR(30) NOT NULL,
  execution_count BIGINT NOT NULL DEFAULT 0,
  buy_quantity BIGINT NOT NULL DEFAULT 0,
  sell_quantity BIGINT NOT NULL DEFAULT 0,
  buy_amount DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  sell_amount DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  net_cash_flow DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  execution_amount DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  last_executed_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL,
  CONSTRAINT uk_stock_execution_daily_account_run_symbol_account UNIQUE (close_run_id, symbol, account_id),
  CONSTRAINT chk_stock_execution_daily_account_category CHECK (CASE `participant_category` WHEN 'LISTING_UNDERWRITER' THEN 1 WHEN 'AUTO_PARTICIPANT' THEN 1 WHEN 'MANUAL_PARTICIPANT' THEN 1 ELSE 0 END = 1),
  CONSTRAINT chk_stock_execution_daily_account_quantity CHECK (execution_count >= 0 AND buy_quantity >= 0 AND sell_quantity >= 0),
  CONSTRAINT chk_stock_execution_daily_account_amount CHECK (buy_amount >= 0 AND sell_amount >= 0 AND execution_amount >= 0)
);

CREATE INDEX IF NOT EXISTS idx_stock_execution_daily_account_symbol_date ON stock_execution_daily_account_snapshot(symbol, simulation_trade_date, close_run_id, account_id);
CREATE INDEX IF NOT EXISTS idx_stock_execution_daily_account_account_date ON stock_execution_daily_account_snapshot(account_id, simulation_trade_date, close_run_id);

CREATE TABLE IF NOT EXISTS stock_execution_account_day_summary (
  simulation_trade_date DATE NOT NULL,
  account_id BIGINT NOT NULL,
  execution_count BIGINT NOT NULL DEFAULT 0,
  buy_quantity BIGINT NOT NULL DEFAULT 0,
  sell_quantity BIGINT NOT NULL DEFAULT 0,
  gross_amount DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  buy_gross_amount DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  sell_gross_amount DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  buy_net_amount DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  sell_net_amount DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  fee_amount DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  tax_amount DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  realized_profit DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  last_executed_at TIMESTAMP,
  updated_at TIMESTAMP NOT NULL,
  PRIMARY KEY (simulation_trade_date, account_id),
  CONSTRAINT chk_stock_execution_account_day_quantity CHECK (execution_count >= 0 AND buy_quantity >= 0 AND sell_quantity >= 0),
  CONSTRAINT chk_stock_execution_account_day_amount CHECK (
    gross_amount >= 0
    AND buy_gross_amount >= 0
    AND sell_gross_amount >= 0
    AND buy_net_amount >= 0
    AND sell_net_amount >= 0
    AND fee_amount >= 0
    AND tax_amount >= 0
  )
);

CREATE INDEX IF NOT EXISTS idx_stock_execution_account_day_account_date ON stock_execution_account_day_summary(account_id, simulation_trade_date);

CREATE TABLE IF NOT EXISTS stock_auto_participant (
  user_key VARCHAR(64) NOT NULL PRIMARY KEY,
  display_name VARCHAR(80) NOT NULL,
  enabled BOOLEAN NOT NULL,
  profile_type VARCHAR(40) NOT NULL DEFAULT 'NOISE_TRADER',
  recurring_cash_amount DECIMAL(19,2) NULL,
  recurring_cash_interval_value DECIMAL(12,4) NULL,
  recurring_cash_interval_unit VARCHAR(20) NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  withdrawn_at TIMESTAMP NULL,
  CONSTRAINT chk_stock_auto_participant_profile_type CHECK (
    CASE `profile_type`
      WHEN 'NEWS_REACTIVE' THEN 1
      WHEN 'MOMENTUM_FOLLOWER' THEN 1
      WHEN 'CONTRARIAN' THEN 1
      WHEN 'LOSS_AVERSE' THEN 1
      WHEN 'OVERCONFIDENT' THEN 1
      WHEN 'HERD_FOLLOWER' THEN 1
      WHEN 'MARKET_MAKER' THEN 1
      WHEN 'NOISE_TRADER' THEN 1
      WHEN 'VALUE_ANCHOR' THEN 1
      WHEN 'SCALPER' THEN 1
      WHEN 'DAY_TRADER' THEN 1
      WHEN 'SWING_TRADER' THEN 1
      WHEN 'LONG_TERM_HOLDER' THEN 1
      WHEN 'PAYDAY_ACCUMULATOR' THEN 1
      WHEN 'DIVIDEND_REINVESTOR' THEN 1
      WHEN 'LIMIT_DOWN_TRAPPED' THEN 1
      WHEN 'AVERAGE_DOWN_BUYER' THEN 1
      WHEN 'STOP_LOSS_TRADER' THEN 1
      WHEN 'FOMO_BUYER' THEN 1
      WHEN 'PANIC_SELLER' THEN 1
      WHEN 'DIP_BUYER' THEN 1
      WHEN 'PROFIT_LOCKER' THEN 1
      WHEN 'LIQUIDITY_AVOIDANT' THEN 1
      WHEN 'CASH_DEFENSIVE' THEN 1
      WHEN 'WHALE' THEN 1
      WHEN 'SMALL_DIVERSIFIER' THEN 1
      WHEN 'OBSERVER' THEN 1
      ELSE 0
    END = 1
  ),
  CONSTRAINT chk_stock_auto_participant_recurring_cash_amount CHECK (recurring_cash_amount IS NULL OR recurring_cash_amount >= 0),
  CONSTRAINT chk_stock_auto_participant_recurring_cash_interval CHECK (recurring_cash_interval_value IS NULL OR (recurring_cash_interval_value >= 0 AND recurring_cash_interval_value <= 1000)),
  CONSTRAINT chk_stock_auto_participant_recurring_cash_unit CHECK (
    recurring_cash_interval_unit IS NULL OR
    CASE `recurring_cash_interval_unit`
      WHEN 'SECOND' THEN 1
      WHEN 'MINUTE' THEN 1
      WHEN 'HOUR' THEN 1
      WHEN 'DAY' THEN 1
      WHEN 'MONTH' THEN 1
      WHEN 'YEAR' THEN 1
      ELSE 0
    END = 1
  ),
  CONSTRAINT chk_stock_auto_participant_recurring_cash_complete CHECK (
    recurring_cash_amount IS NULL
    OR recurring_cash_amount = 0
    OR (recurring_cash_interval_value IS NOT NULL AND recurring_cash_interval_value > 0 AND recurring_cash_interval_unit IS NOT NULL)
  )
);

CREATE INDEX IF NOT EXISTS idx_stock_auto_participant_active ON stock_auto_participant(withdrawn_at, enabled, user_key);
CREATE INDEX IF NOT EXISTS idx_stock_auto_participant_profile_active ON stock_auto_participant(withdrawn_at, profile_type, enabled, user_key);

CREATE TABLE IF NOT EXISTS stock_auto_participant_profile_config (
  profile_type VARCHAR(40) NOT NULL PRIMARY KEY,
  news_weight DECIMAL(8,4) DEFAULT NULL,
  momentum_weight DECIMAL(8,4) DEFAULT NULL,
  contrarian_weight DECIMAL(8,4) DEFAULT NULL,
  loss_aversion_weight DECIMAL(8,4) DEFAULT NULL,
  herding_weight DECIMAL(8,4) DEFAULT NULL,
  market_making_weight DECIMAL(8,4) DEFAULT NULL,
  overconfidence_weight DECIMAL(8,4) DEFAULT NULL,
  noise_weight DECIMAL(8,4) DEFAULT NULL,
  panic_sell_weight DECIMAL(8,4) DEFAULT NULL,
  dip_buy_weight DECIMAL(8,4) DEFAULT NULL,
  order_multiplier DECIMAL(8,4) NOT NULL,
  aggression_multiplier DECIMAL(8,4) NOT NULL,
  price_pressure_sensitivity DECIMAL(8,4) NOT NULL DEFAULT 1.0000,
  order_ttl_multiplier DECIMAL(8,4) NOT NULL DEFAULT 1.0000,
  quantity_multiplier DECIMAL(8,4) NOT NULL,
  holding_patience_weight DECIMAL(8,4) NOT NULL,
  deep_loss_hold_weight DECIMAL(8,4) NOT NULL,
  profit_taking_weight DECIMAL(8,4) NOT NULL DEFAULT 0.0000,
  recurring_deposit_amount DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  recurring_deposit_interval_days INT NOT NULL DEFAULT 30,
  recurring_deposit_interval_value DECIMAL(12,4) NOT NULL DEFAULT 30.0000,
  recurring_deposit_interval_unit VARCHAR(20) NOT NULL DEFAULT 'DAY',
  updated_at TIMESTAMP NOT NULL,
  CONSTRAINT chk_stock_auto_profile_config_type CHECK (
    CASE `profile_type`
      WHEN 'NEWS_REACTIVE' THEN 1
      WHEN 'MOMENTUM_FOLLOWER' THEN 1
      WHEN 'CONTRARIAN' THEN 1
      WHEN 'LOSS_AVERSE' THEN 1
      WHEN 'OVERCONFIDENT' THEN 1
      WHEN 'HERD_FOLLOWER' THEN 1
      WHEN 'MARKET_MAKER' THEN 1
      WHEN 'NOISE_TRADER' THEN 1
      WHEN 'VALUE_ANCHOR' THEN 1
      WHEN 'SCALPER' THEN 1
      WHEN 'DAY_TRADER' THEN 1
      WHEN 'SWING_TRADER' THEN 1
      WHEN 'LONG_TERM_HOLDER' THEN 1
      WHEN 'PAYDAY_ACCUMULATOR' THEN 1
      WHEN 'DIVIDEND_REINVESTOR' THEN 1
      WHEN 'LIMIT_DOWN_TRAPPED' THEN 1
      WHEN 'AVERAGE_DOWN_BUYER' THEN 1
      WHEN 'STOP_LOSS_TRADER' THEN 1
      WHEN 'FOMO_BUYER' THEN 1
      WHEN 'PANIC_SELLER' THEN 1
      WHEN 'DIP_BUYER' THEN 1
      WHEN 'PROFIT_LOCKER' THEN 1
      WHEN 'LIQUIDITY_AVOIDANT' THEN 1
      WHEN 'CASH_DEFENSIVE' THEN 1
      WHEN 'WHALE' THEN 1
      WHEN 'SMALL_DIVERSIFIER' THEN 1
      WHEN 'OBSERVER' THEN 1
      ELSE 0
    END = 1
  ),
  CONSTRAINT chk_stock_auto_profile_news_weight CHECK (news_weight IS NULL OR (news_weight >= 0 AND news_weight <= 1)),
  CONSTRAINT chk_stock_auto_profile_momentum_weight CHECK (momentum_weight IS NULL OR (momentum_weight >= 0 AND momentum_weight <= 1)),
  CONSTRAINT chk_stock_auto_profile_contrarian_weight CHECK (contrarian_weight IS NULL OR (contrarian_weight >= 0 AND contrarian_weight <= 1)),
  CONSTRAINT chk_stock_auto_profile_loss_aversion_weight CHECK (loss_aversion_weight IS NULL OR (loss_aversion_weight >= 0 AND loss_aversion_weight <= 1)),
  CONSTRAINT chk_stock_auto_profile_herding_weight CHECK (herding_weight IS NULL OR (herding_weight >= 0 AND herding_weight <= 1)),
  CONSTRAINT chk_stock_auto_profile_market_making_weight CHECK (market_making_weight IS NULL OR (market_making_weight >= 0 AND market_making_weight <= 1)),
  CONSTRAINT chk_stock_auto_profile_overconfidence_weight CHECK (overconfidence_weight IS NULL OR (overconfidence_weight >= 0 AND overconfidence_weight <= 1)),
  CONSTRAINT chk_stock_auto_profile_noise_weight CHECK (noise_weight IS NULL OR (noise_weight >= 0 AND noise_weight <= 1)),
  CONSTRAINT chk_stock_auto_profile_panic_sell_weight CHECK (panic_sell_weight IS NULL OR (panic_sell_weight >= 0 AND panic_sell_weight <= 1)),
  CONSTRAINT chk_stock_auto_profile_dip_buy_weight CHECK (dip_buy_weight IS NULL OR (dip_buy_weight >= 0 AND dip_buy_weight <= 1)),
  CONSTRAINT chk_stock_auto_profile_order_multiplier CHECK (order_multiplier >= 0 AND order_multiplier <= 5),
  CONSTRAINT chk_stock_auto_profile_aggression_multiplier CHECK (aggression_multiplier >= 0 AND aggression_multiplier <= 5),
  CONSTRAINT chk_stock_auto_profile_price_pressure_sensitivity CHECK (price_pressure_sensitivity >= 0 AND price_pressure_sensitivity <= 2),
  CONSTRAINT chk_stock_auto_profile_order_ttl_multiplier CHECK (order_ttl_multiplier >= 0.1 AND order_ttl_multiplier <= 10),
  CONSTRAINT chk_stock_auto_profile_quantity_multiplier CHECK (quantity_multiplier >= 0 AND quantity_multiplier <= 5),
  CONSTRAINT chk_stock_auto_profile_holding_patience CHECK (holding_patience_weight >= 0 AND holding_patience_weight <= 1),
  CONSTRAINT chk_stock_auto_profile_deep_loss_hold CHECK (deep_loss_hold_weight >= 0 AND deep_loss_hold_weight <= 1),
  CONSTRAINT chk_stock_auto_profile_profit_taking CHECK (profit_taking_weight >= 0 AND profit_taking_weight <= 1),
  CONSTRAINT chk_stock_auto_profile_recurring_deposit CHECK (recurring_deposit_amount >= 0),
  CONSTRAINT chk_stock_auto_profile_recurring_interval CHECK (recurring_deposit_interval_days >= 1),
  CONSTRAINT chk_stock_auto_profile_recurring_interval_value CHECK (recurring_deposit_interval_value >= 0 AND recurring_deposit_interval_value <= 1000),
  CONSTRAINT chk_stock_auto_profile_recurring_interval_unit CHECK (
    CASE `recurring_deposit_interval_unit`
      WHEN 'SECOND' THEN 1
      WHEN 'MINUTE' THEN 1
      WHEN 'HOUR' THEN 1
      WHEN 'DAY' THEN 1
      WHEN 'MONTH' THEN 1
      WHEN 'YEAR' THEN 1
      ELSE 0
    END = 1
  ),
  CONSTRAINT chk_stock_auto_profile_recurring_interval_complete CHECK (
    recurring_deposit_amount = 0
    OR (recurring_deposit_interval_value > 0 AND recurring_deposit_interval_unit IS NOT NULL)
  )
);

CREATE TABLE IF NOT EXISTS stock_auto_participant_event_profile_config (
  profile_type VARCHAR(40) NOT NULL PRIMARY KEY,
  shareholder_subscription_rate DECIMAL(8,4) NOT NULL DEFAULT 0.4500,
  public_offering_subscription_rate DECIMAL(8,4) NOT NULL DEFAULT 0.2000,
  max_cash_allocation_rate DECIMAL(8,4) NOT NULL DEFAULT 0.2000,
  updated_at TIMESTAMP NOT NULL,
  CONSTRAINT chk_stock_auto_event_profile_type CHECK (
    CASE `profile_type`
      WHEN 'NEWS_REACTIVE' THEN 1
      WHEN 'MOMENTUM_FOLLOWER' THEN 1
      WHEN 'CONTRARIAN' THEN 1
      WHEN 'LOSS_AVERSE' THEN 1
      WHEN 'OVERCONFIDENT' THEN 1
      WHEN 'HERD_FOLLOWER' THEN 1
      WHEN 'MARKET_MAKER' THEN 1
      WHEN 'NOISE_TRADER' THEN 1
      WHEN 'VALUE_ANCHOR' THEN 1
      WHEN 'SCALPER' THEN 1
      WHEN 'DAY_TRADER' THEN 1
      WHEN 'SWING_TRADER' THEN 1
      WHEN 'LONG_TERM_HOLDER' THEN 1
      WHEN 'PAYDAY_ACCUMULATOR' THEN 1
      WHEN 'DIVIDEND_REINVESTOR' THEN 1
      WHEN 'LIMIT_DOWN_TRAPPED' THEN 1
      WHEN 'AVERAGE_DOWN_BUYER' THEN 1
      WHEN 'STOP_LOSS_TRADER' THEN 1
      WHEN 'FOMO_BUYER' THEN 1
      WHEN 'PANIC_SELLER' THEN 1
      WHEN 'DIP_BUYER' THEN 1
      WHEN 'PROFIT_LOCKER' THEN 1
      WHEN 'LIQUIDITY_AVOIDANT' THEN 1
      WHEN 'CASH_DEFENSIVE' THEN 1
      WHEN 'WHALE' THEN 1
      WHEN 'SMALL_DIVERSIFIER' THEN 1
      WHEN 'OBSERVER' THEN 1
      ELSE 0
    END = 1
  ),
  CONSTRAINT chk_stock_auto_event_profile_shareholder_rate CHECK (shareholder_subscription_rate >= 0 AND shareholder_subscription_rate <= 1),
  CONSTRAINT chk_stock_auto_event_profile_public_rate CHECK (public_offering_subscription_rate >= 0 AND public_offering_subscription_rate <= 1),
  CONSTRAINT chk_stock_auto_event_profile_cash_rate CHECK (max_cash_allocation_rate >= 0 AND max_cash_allocation_rate <= 1)
);

CREATE TABLE IF NOT EXISTS stock_virtual_market_config (
  symbol VARCHAR(20) NOT NULL PRIMARY KEY,
  enabled BOOLEAN NOT NULL,
  market_status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
  updated_at TIMESTAMP NOT NULL,
  CONSTRAINT chk_stock_virtual_market_status CHECK (CASE `market_status` WHEN 'OPEN' THEN 1 WHEN 'CLOSED' THEN 1 WHEN 'HALTED' THEN 1 WHEN 'CIRCUIT_BREAKER' THEN 1 ELSE 0 END = 1)
);

CREATE INDEX IF NOT EXISTS idx_stock_virtual_market_enabled ON stock_virtual_market_config(enabled, market_status, symbol);

CREATE TABLE IF NOT EXISTS stock_order_book_market_config (
  symbol VARCHAR(20) NOT NULL PRIMARY KEY,
  enabled BOOLEAN NOT NULL,
  market_status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
  updated_at TIMESTAMP NOT NULL,
  CONSTRAINT chk_stock_order_book_market_status CHECK (CASE `market_status` WHEN 'OPEN' THEN 1 WHEN 'CLOSED' THEN 1 WHEN 'HALTED' THEN 1 WHEN 'CIRCUIT_BREAKER' THEN 1 ELSE 0 END = 1)
);

CREATE INDEX IF NOT EXISTS idx_stock_order_book_market_enabled ON stock_order_book_market_config(enabled, market_status, symbol);

CREATE TABLE IF NOT EXISTS stock_market_business_state (
  state_id VARCHAR(20) NOT NULL PRIMARY KEY,
  active_business_date DATE NOT NULL,
  preparing_business_date DATE NULL,
  raw_simulation_date DATE NOT NULL,
  version BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  CONSTRAINT chk_stock_market_business_state_version CHECK (version >= 0)
);

CREATE TABLE IF NOT EXISTS stock_market_session_fence (
  market_type VARCHAR(20) NOT NULL,
  symbol VARCHAR(20) NOT NULL,
  business_date DATE NOT NULL,
  session_epoch BIGINT NOT NULL,
  session_state VARCHAR(20) NOT NULL,
  state_changed_at TIMESTAMP NOT NULL,
  version BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  PRIMARY KEY (market_type, symbol),
  CONSTRAINT chk_stock_market_session_fence_market_type CHECK (
    CASE `market_type` WHEN 'VIRTUAL_PRICE' THEN 1 WHEN 'ORDER_BOOK' THEN 1 ELSE 0 END = 1
  ),
  CONSTRAINT chk_stock_market_session_fence_state CHECK (
    CASE `session_state` WHEN 'OPEN' THEN 1 WHEN 'CLOSING' THEN 1 WHEN 'CLOSED' THEN 1 WHEN 'PREPARING' THEN 1 ELSE 0 END = 1
  ),
  CONSTRAINT chk_stock_market_session_fence_epoch CHECK (session_epoch > 0),
  CONSTRAINT chk_stock_market_session_fence_version CHECK (version >= 0)
);

CREATE INDEX IF NOT EXISTS idx_stock_market_session_fence_state
  ON stock_market_session_fence(business_date, session_state, market_type, symbol);

CREATE TABLE IF NOT EXISTS stock_auto_market_config (
  symbol VARCHAR(20) NOT NULL PRIMARY KEY,
  enabled BOOLEAN NOT NULL,
  primary_regime_count_1_weight INT NOT NULL DEFAULT 0,
  primary_regime_count_2_weight INT NOT NULL DEFAULT 0,
  primary_regime_count_3_weight INT NOT NULL DEFAULT 0,
  primary_regime_count_4_weight INT NOT NULL DEFAULT 100,
  primary_price_pressure_bias INT NOT NULL DEFAULT 0,
  primary_asset_preference_pressure_bias INT NOT NULL DEFAULT 0,
  primary_volatility_pressure_bias INT NOT NULL DEFAULT 0,
  primary_liquidity_pressure_bias INT NOT NULL DEFAULT 0,
  primary_execution_aggression_pressure_bias INT NOT NULL DEFAULT 0,
  secondary_price_pressure_bias INT NOT NULL DEFAULT 0,
  secondary_asset_preference_pressure_bias INT NOT NULL DEFAULT 0,
  secondary_volatility_pressure_bias INT NOT NULL DEFAULT 0,
  secondary_liquidity_pressure_bias INT NOT NULL DEFAULT 0,
  secondary_execution_aggression_pressure_bias INT NOT NULL DEFAULT 0,
  max_order_quantity INT NOT NULL,
  order_ttl_seconds INT NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  CONSTRAINT chk_stock_auto_market_regime_count_weights CHECK (
    primary_regime_count_1_weight between 0 and 100
    and primary_regime_count_2_weight between 0 and 100
    and primary_regime_count_3_weight between 0 and 100
    and primary_regime_count_4_weight between 0 and 100
    and primary_regime_count_1_weight + primary_regime_count_2_weight
      + primary_regime_count_3_weight + primary_regime_count_4_weight > 0
  ),
  CONSTRAINT chk_stock_auto_market_primary_price_bias CHECK (primary_price_pressure_bias between -100 and 100),
  CONSTRAINT chk_stock_auto_market_primary_asset_bias CHECK (primary_asset_preference_pressure_bias between -100 and 100),
  CONSTRAINT chk_stock_auto_market_primary_volatility_bias CHECK (primary_volatility_pressure_bias between -100 and 100),
  CONSTRAINT chk_stock_auto_market_primary_liquidity_bias CHECK (primary_liquidity_pressure_bias between -100 and 100),
  CONSTRAINT chk_stock_auto_market_primary_aggression_bias CHECK (primary_execution_aggression_pressure_bias between -100 and 100),
  CONSTRAINT chk_stock_auto_market_secondary_price_bias CHECK (secondary_price_pressure_bias between -100 and 100),
  CONSTRAINT chk_stock_auto_market_secondary_asset_bias CHECK (secondary_asset_preference_pressure_bias between -100 and 100),
  CONSTRAINT chk_stock_auto_market_secondary_volatility_bias CHECK (secondary_volatility_pressure_bias between -100 and 100),
  CONSTRAINT chk_stock_auto_market_secondary_liquidity_bias CHECK (secondary_liquidity_pressure_bias between -100 and 100),
  CONSTRAINT chk_stock_auto_market_secondary_aggression_bias CHECK (secondary_execution_aggression_pressure_bias between -100 and 100),
  CONSTRAINT chk_stock_auto_market_max_order_quantity CHECK (max_order_quantity > 0),
  CONSTRAINT chk_stock_auto_market_order_ttl_seconds CHECK (order_ttl_seconds > 0)
);

CREATE INDEX IF NOT EXISTS idx_stock_auto_market_enabled ON stock_auto_market_config(enabled, symbol);

CREATE TABLE IF NOT EXISTS stock_order_book_daily_regime (
  symbol VARCHAR(20) NOT NULL,
  simulation_trade_date DATE NOT NULL,
  regime_phase VARCHAR(20) NOT NULL,
  source_regime_phase VARCHAR(20) NULL,
  price_pressure INT NOT NULL,
  asset_preference_pressure INT NOT NULL,
  volatility_pressure INT NOT NULL,
  liquidity_pressure INT NOT NULL,
  execution_aggression_pressure INT NOT NULL,
  seed BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  PRIMARY KEY (symbol, simulation_trade_date, regime_phase),
  CONSTRAINT chk_stock_order_book_daily_regime_phase CHECK (CASE regime_phase WHEN 'SLOT_0600' THEN 1 WHEN 'SLOT_0900' THEN 1 WHEN 'SLOT_1200' THEN 1 WHEN 'SLOT_1500' THEN 1 ELSE 0 END = 1),
  CONSTRAINT chk_stock_order_book_daily_regime_source_phase CHECK (
    source_regime_phase is null
    or CASE source_regime_phase WHEN 'SLOT_0600' THEN 1 WHEN 'SLOT_0900' THEN 1 WHEN 'SLOT_1200' THEN 1 WHEN 'SLOT_1500' THEN 1 ELSE 0 END = 1
  ),
  CONSTRAINT chk_stock_order_book_daily_regime_price CHECK (price_pressure between -100 and 100),
  CONSTRAINT chk_stock_order_book_daily_regime_asset CHECK (asset_preference_pressure between -100 and 100),
  CONSTRAINT chk_stock_order_book_daily_regime_volatility CHECK (volatility_pressure between -100 and 100),
  CONSTRAINT chk_stock_order_book_daily_regime_liquidity CHECK (liquidity_pressure between -100 and 100),
  CONSTRAINT chk_stock_order_book_daily_regime_aggression CHECK (execution_aggression_pressure between -100 and 100)
);

CREATE INDEX IF NOT EXISTS idx_stock_order_book_daily_regime_date ON stock_order_book_daily_regime(simulation_trade_date, regime_phase, symbol);

CREATE TABLE IF NOT EXISTS stock_order_book_regime_modifier (
  symbol VARCHAR(20) NOT NULL,
  simulation_trade_date DATE NOT NULL,
  regime_phase VARCHAR(20) NOT NULL,
  modifier_window_start_at TIMESTAMP NOT NULL,
  price_pressure INT NOT NULL,
  asset_preference_pressure INT NOT NULL,
  volatility_pressure INT NOT NULL,
  liquidity_pressure INT NOT NULL,
  execution_aggression_pressure INT NOT NULL,
  seed BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  PRIMARY KEY (symbol, simulation_trade_date, regime_phase, modifier_window_start_at),
  CONSTRAINT chk_stock_order_book_regime_modifier_phase CHECK (CASE regime_phase WHEN 'SLOT_0600' THEN 1 WHEN 'SLOT_0900' THEN 1 WHEN 'SLOT_1200' THEN 1 WHEN 'SLOT_1500' THEN 1 ELSE 0 END = 1),
  CONSTRAINT chk_stock_order_book_regime_modifier_price CHECK (price_pressure between -100 and 100),
  CONSTRAINT chk_stock_order_book_regime_modifier_asset CHECK (asset_preference_pressure between -100 and 100),
  CONSTRAINT chk_stock_order_book_regime_modifier_volatility CHECK (volatility_pressure between -100 and 100),
  CONSTRAINT chk_stock_order_book_regime_modifier_liquidity CHECK (liquidity_pressure between -100 and 100),
  CONSTRAINT chk_stock_order_book_regime_modifier_aggression CHECK (execution_aggression_pressure between -100 and 100)
);

CREATE INDEX IF NOT EXISTS idx_stock_order_book_regime_modifier_window ON stock_order_book_regime_modifier(simulation_trade_date, regime_phase, modifier_window_start_at, symbol);

CREATE TABLE IF NOT EXISTS stock_listing_auto_account_config (
  symbol VARCHAR(20) NOT NULL PRIMARY KEY,
  user_key VARCHAR(64) NOT NULL UNIQUE,
  display_name VARCHAR(80) NOT NULL,
  enabled BOOLEAN NOT NULL,
  position_side VARCHAR(20) NOT NULL,
  operation_mode VARCHAR(30) NOT NULL,
  strategy_profile VARCHAR(30) NOT NULL,
  initial_inventory_quantity BIGINT NOT NULL,
  initial_issue_price DECIMAL(19,2) NOT NULL,
  max_order_quantity INT NOT NULL,
  order_ttl_seconds INT NOT NULL,
  price_offset_ticks INT NOT NULL,
  target_spread_ticks INT NOT NULL,
  inventory_skew_ticks INT NOT NULL,
  minimum_profit_rate DECIMAL(8,4) NOT NULL,
  aggressive_unwind_threshold DECIMAL(8,4) NOT NULL,
  aggressive_order_ratio DECIMAL(8,4) NOT NULL,
  target_buy_quantity BIGINT NOT NULL,
  target_sell_quantity BIGINT NOT NULL,
  target_holding_quantity BIGINT NOT NULL,
  inventory_band_quantity BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  CONSTRAINT chk_stock_listing_auto_account_position CHECK (CASE `position_side` WHEN 'SELL_ONLY' THEN 1 WHEN 'BUY_ONLY' THEN 1 WHEN 'TWO_SIDED' THEN 1 ELSE 0 END = 1),
  CONSTRAINT chk_stock_listing_auto_account_operation_mode CHECK (operation_mode IN ('UNDERWRITER_RETURN', 'LIQUIDITY_PROVIDER', 'HYBRID')),
  CONSTRAINT chk_stock_listing_auto_account_strategy_profile CHECK (strategy_profile IN ('LIQUIDITY_FIRST', 'BALANCED', 'RETURN_FIRST')),
  CONSTRAINT chk_stock_listing_auto_account_initial_quantity CHECK (initial_inventory_quantity > 0),
  CONSTRAINT chk_stock_listing_auto_account_initial_price CHECK (initial_issue_price > 0),
  CONSTRAINT chk_stock_listing_auto_account_max_order_quantity CHECK (max_order_quantity > 0),
  CONSTRAINT chk_stock_listing_auto_account_order_ttl_seconds CHECK (order_ttl_seconds > 0),
  CONSTRAINT chk_stock_listing_auto_account_price_offset CHECK (price_offset_ticks >= 0),
  CONSTRAINT chk_stock_listing_auto_account_target_spread CHECK (target_spread_ticks BETWEEN 1 AND 50),
  CONSTRAINT chk_stock_listing_auto_account_inventory_skew CHECK (inventory_skew_ticks BETWEEN 0 AND 50),
  CONSTRAINT chk_stock_listing_auto_account_minimum_profit CHECK (minimum_profit_rate BETWEEN 0 AND 100),
  CONSTRAINT chk_stock_listing_auto_account_unwind_threshold CHECK (aggressive_unwind_threshold BETWEEN 0 AND 1),
  CONSTRAINT chk_stock_listing_auto_account_aggressive_ratio CHECK (aggressive_order_ratio BETWEEN 0 AND 1),
  CONSTRAINT chk_stock_listing_auto_account_target_buy CHECK (target_buy_quantity >= 0),
  CONSTRAINT chk_stock_listing_auto_account_target_sell CHECK (target_sell_quantity >= 0),
  CONSTRAINT chk_stock_listing_auto_account_target_holding CHECK (target_holding_quantity >= 0),
  CONSTRAINT chk_stock_listing_auto_account_inventory_band CHECK (inventory_band_quantity >= 0)
);

CREATE INDEX IF NOT EXISTS idx_stock_listing_auto_account_enabled ON stock_listing_auto_account_config(enabled, symbol);

CREATE TABLE IF NOT EXISTS stock_auto_participant_symbol_config (
  user_key VARCHAR(64) NOT NULL,
  symbol VARCHAR(20) NOT NULL,
  enabled BOOLEAN NOT NULL,
  intensity INT NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  PRIMARY KEY (user_key, symbol),
  CONSTRAINT chk_stock_auto_participant_symbol_intensity CHECK (intensity between 1 and 10)
);

CREATE INDEX IF NOT EXISTS idx_stock_auto_participant_symbol_enabled ON stock_auto_participant_symbol_config(enabled, symbol, user_key);
CREATE INDEX IF NOT EXISTS idx_stock_auto_participant_symbol_lookup ON stock_auto_participant_symbol_config(symbol, user_key);
CREATE INDEX IF NOT EXISTS idx_stock_auto_participant_symbol_user_enabled ON stock_auto_participant_symbol_config(user_key, enabled, symbol);

CREATE TABLE IF NOT EXISTS stock_auto_participant_order_schedule (
  user_key VARCHAR(64) NOT NULL,
  profile_type VARCHAR(40) NOT NULL,
  next_run_at TIMESTAMP NOT NULL,
  last_run_at TIMESTAMP NULL,
  lease_until TIMESTAMP NULL,
  lease_owner VARCHAR(80) NULL,
  run_interval_seconds INT NOT NULL,
  priority INT NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  PRIMARY KEY (user_key),
  CONSTRAINT chk_stock_auto_order_schedule_interval CHECK (run_interval_seconds > 0),
  CONSTRAINT chk_stock_auto_order_schedule_priority CHECK (priority between 1 and 100)
);

CREATE INDEX IF NOT EXISTS idx_stock_auto_order_schedule_due ON stock_auto_participant_order_schedule(next_run_at, lease_until, priority, user_key);
CREATE INDEX IF NOT EXISTS idx_stock_auto_order_schedule_profile_due ON stock_auto_participant_order_schedule(profile_type, next_run_at, user_key);

CREATE TABLE IF NOT EXISTS stock_instrument_report_event (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  symbol VARCHAR(20) NOT NULL,
  event_type VARCHAR(20) NOT NULL,
  title VARCHAR(120) NULL,
  summary VARCHAR(1000) NULL,
  score INT NULL,
  rise_reason VARCHAR(500) NULL,
  fall_reason VARCHAR(500) NULL,
  delete_reason VARCHAR(255) NULL,
  created_by VARCHAR(64) NULL,
  created_at TIMESTAMP NOT NULL,
  CONSTRAINT chk_stock_report_event_type CHECK (CASE `event_type` WHEN 'PUBLISH' THEN 1 WHEN 'UPDATE' THEN 1 WHEN 'DELETE' THEN 1 ELSE 0 END = 1),
  CONSTRAINT chk_stock_report_score CHECK (score IS NULL OR score between 1 and 10),
  CONSTRAINT chk_stock_report_content_scope CHECK ((event_type = 'DELETE' AND title IS NULL AND summary IS NULL AND score IS NULL AND rise_reason IS NULL AND fall_reason IS NULL) OR (event_type IN ('PUBLISH', 'UPDATE') AND title IS NOT NULL AND summary IS NOT NULL AND score IS NOT NULL))
);

CREATE INDEX IF NOT EXISTS idx_stock_report_symbol_time ON stock_instrument_report_event(symbol, created_at, id);

CREATE TABLE IF NOT EXISTS portfolio_snapshot (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  close_cycle_id BIGINT NULL,
  close_run_id BIGINT NULL,
  account_id BIGINT NOT NULL,
  snapshot_date DATE NOT NULL,
  total_asset DECIMAL(19,2) NOT NULL,
  cash_balance DECIMAL(19,2) NOT NULL,
  pending_subscription_asset DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  market_value DECIMAL(19,2) NOT NULL,
  holding_quantity BIGINT NULL,
  reserved_sell_quantity BIGINT NULL,
  holding_position_count BIGINT NULL,
  net_contribution DECIMAL(19,2) NULL,
  total_profit DECIMAL(19,2) NULL,
  return_rate DECIMAL(19,8) NULL,
  return_rate_status VARCHAR(40) NOT NULL DEFAULT 'LEGACY_UNVERIFIED',
  input_hash VARCHAR(64) NULL,
  calculation_version VARCHAR(40) NULL,
  data_quality_status VARCHAR(20) NULL,
  source_build_version VARCHAR(100) NULL,
  created_at TIMESTAMP NOT NULL,
  CONSTRAINT uk_portfolio_snapshot_account_date UNIQUE (account_id, snapshot_date),
  CONSTRAINT uk_portfolio_snapshot_cycle_account UNIQUE (close_cycle_id, account_id),
  CONSTRAINT chk_portfolio_snapshot_total_asset_non_negative CHECK (total_asset >= 0),
  CONSTRAINT chk_portfolio_snapshot_cash_balance_non_negative CHECK (cash_balance >= 0),
  CONSTRAINT chk_portfolio_snapshot_pending_subscription_non_negative CHECK (
    pending_subscription_asset >= 0
  ),
  CONSTRAINT chk_portfolio_snapshot_market_value_non_negative CHECK (market_value >= 0),
  CONSTRAINT chk_portfolio_snapshot_asset_composition CHECK (
    total_asset = cash_balance + pending_subscription_asset + market_value
  ),
  CONSTRAINT chk_portfolio_snapshot_return_contract CHECK (
    (return_rate_status = 'LEGACY_UNVERIFIED' AND net_contribution IS NULL AND total_profit IS NULL)
    OR (
      net_contribution IS NOT NULL
      AND total_profit IS NOT NULL
      AND total_profit = total_asset - net_contribution
      AND (
        (return_rate_status = 'DEFINED' AND net_contribution > 0 AND return_rate IS NOT NULL)
        OR (
          return_rate_status = 'UNDEFINED_ZERO_CONTRIBUTION'
          AND net_contribution = 0
          AND return_rate IS NULL
        )
        OR (
          return_rate_status = 'UNDEFINED_NEGATIVE_CONTRIBUTION'
          AND net_contribution < 0
          AND return_rate IS NULL
        )
      )
    )
  ),
  CONSTRAINT chk_portfolio_snapshot_holding_metrics_complete CHECK (
    (holding_quantity IS NULL AND reserved_sell_quantity IS NULL AND holding_position_count IS NULL)
    OR (
      holding_quantity IS NOT NULL
      AND reserved_sell_quantity IS NOT NULL
      AND holding_position_count IS NOT NULL
      AND holding_quantity >= 0
      AND reserved_sell_quantity >= 0
      AND reserved_sell_quantity <= holding_quantity
      AND holding_position_count >= 0
    )
  ),
  CONSTRAINT chk_portfolio_snapshot_input_hash CHECK (input_hash IS NULL OR char_length(input_hash) = 64),
  CONSTRAINT chk_portfolio_snapshot_data_quality CHECK (
    data_quality_status IS NULL OR data_quality_status IN ('VERIFIED', 'WARNING', 'INVALID')
  )
);

CREATE INDEX IF NOT EXISTS idx_portfolio_snapshot_date_return ON portfolio_snapshot(snapshot_date, return_rate);
CREATE INDEX IF NOT EXISTS idx_portfolio_snapshot_close_run ON portfolio_snapshot(close_run_id, account_id);
