CREATE SCHEMA IF NOT EXISTS STOCK_BATCH_METADATA;
USE STOCK_BATCH_METADATA;

CREATE TABLE IF NOT EXISTS STOCK_BATCH_JOB_METADATA_ARCHIVE (
  JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
  JOB_INSTANCE_ID BIGINT NOT NULL,
  JOB_NAME VARCHAR(100) NOT NULL,
  JOB_KEY VARCHAR(32) NOT NULL,
  STATUS VARCHAR(10) NOT NULL,
  CREATE_TIME DATETIME(6) NOT NULL,
  START_TIME DATETIME(6) DEFAULT NULL,
  END_TIME DATETIME(6) NOT NULL,
  EXIT_CODE VARCHAR(2500),
  EXIT_MESSAGE VARCHAR(2500),
  IDENTIFYING_PARAMETERS VARCHAR(4000) NOT NULL,
  STEP_COUNT BIGINT NOT NULL,
  READ_COUNT BIGINT NOT NULL,
  WRITE_COUNT BIGINT NOT NULL,
  FILTER_COUNT BIGINT NOT NULL,
  COMMIT_COUNT BIGINT NOT NULL,
  ROLLBACK_COUNT BIGINT NOT NULL,
  SKIP_COUNT BIGINT NOT NULL,
  ARCHIVED_AT DATETIME(6) NOT NULL,
  PURGED_AT DATETIME(6) DEFAULT NULL,
  KEY idx_stock_batch_metadata_archive_instance (JOB_INSTANCE_ID),
  KEY idx_stock_batch_metadata_archive_time (ARCHIVED_AT, JOB_EXECUTION_ID)
) ENGINE=InnoDB;

SET @retention_index_exists = (
    SELECT COUNT(*)
      FROM information_schema.statistics
     WHERE table_schema = DATABASE()
       AND table_name = 'BATCH_JOB_EXECUTION'
       AND index_name = 'idx_batch_job_execution_retention'
);
SET @retention_index_sql = IF(
    @retention_index_exists = 0,
    'CREATE INDEX idx_batch_job_execution_retention ON BATCH_JOB_EXECUTION(STATUS, END_TIME, JOB_INSTANCE_ID)',
    'SELECT 1'
);
PREPARE retention_index_statement FROM @retention_index_sql;
EXECUTE retention_index_statement;
DEALLOCATE PREPARE retention_index_statement;
