package stock.batch.service.holdingcleanup.biz;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.util.ReflectionTestUtils;

import stock.batch.service.batch.holdingcleanup.writer.HoldingCleanupWriter;
import stock.batch.service.marketclose.biz.MarketSessionFenceService;
import stock.batch.service.simulation.SimulationClockService;
import stock.batch.service.testsupport.BatchTestDatabaseFactory;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

class HoldingCleanupServiceTest {

    private static final LocalDateTime NOW = LocalDateTime.of(2026, 7, 3, 10, 0);

    private final JdbcTemplate jdbcTemplate = new JdbcTemplate(
            BatchTestDatabaseFactory.createDataSource("holding_cleanup_service_test")
    );
    private final SimulationClockService simulationClockService = mock(SimulationClockService.class);
    private final MarketSessionFenceService marketSessionFenceService = mock(MarketSessionFenceService.class);
    private final HoldingCleanupService holdingCleanupService = new HoldingCleanupService(
            new HoldingCleanupWriter(jdbcTemplate),
            simulationClockService,
            marketSessionFenceService
    );

    @BeforeEach
    void setUp() {
        jdbcTemplate.execute(
                """
                create table if not exists stock_holding (
                  id bigint generated by default as identity primary key,
                  account_id bigint not null,
                  symbol varchar(20) not null,
                  quantity bigint not null,
                  reserved_quantity bigint not null default 0,
                  average_price decimal(19,2) not null,
                  updated_at timestamp not null,
                  constraint uk_stock_holding_account_symbol unique (account_id, symbol),
                  constraint chk_stock_holding_quantity_non_negative check (quantity >= 0),
                  constraint chk_stock_holding_reserved_quantity_valid check (reserved_quantity >= 0 and reserved_quantity <= quantity),
                  constraint chk_stock_holding_average_price_positive check (average_price > 0)
                )
                """
        );
        jdbcTemplate.update("delete from stock_holding");
        when(simulationClockService.currentMarketDateTime()).thenReturn(NOW);
        ReflectionTestUtils.setField(holdingCleanupService, "retentionSimulationDays", 1);
        ReflectionTestUtils.setField(holdingCleanupService, "deleteLimit", 100);
    }

    @Test
    void cleanupEmptyHoldings_deletesOnlyOldRowsWithoutQuantityOrReservation() {
        insertHolding(1L, "OLD_EMPTY", 0, 0, NOW.minusDays(2));
        insertHolding(2L, "RECENT_EMPTY", 0, 0, NOW.minusHours(1));
        insertHolding(3L, "HAS_QUANTITY", 1, 0, NOW.minusDays(2));
        insertHolding(4L, "HAS_RESERVED", 2, 1, NOW.minusDays(2));

        int deletedCount = holdingCleanupService.cleanupEmptyHoldings();

        assertThat(deletedCount).isEqualTo(1);
        assertThat(countBySymbol("OLD_EMPTY")).isZero();
        assertThat(countBySymbol("RECENT_EMPTY")).isEqualTo(1);
        assertThat(countBySymbol("HAS_QUANTITY")).isEqualTo(1);
        assertThat(countBySymbol("HAS_RESERVED")).isEqualTo(1);
    }

    @Test
    void cleanupEmptyHoldings_limitPreventsLargeSingleDelete() {
        ReflectionTestUtils.setField(holdingCleanupService, "deleteLimit", 1);
        insertHolding(1L, "OLD_EMPTY_A", 0, 0, NOW.minusDays(2));
        insertHolding(2L, "OLD_EMPTY_B", 0, 0, NOW.minusDays(2));

        int deletedCount = holdingCleanupService.cleanupEmptyHoldings();

        assertThat(deletedCount).isEqualTo(1);
        assertThat(countAll()).isEqualTo(1);
    }

    @Test
    void validateVolumeConfiguration_deleteLimitAboveSafeMaximum_rejectsStartup() {
        ReflectionTestUtils.setField(holdingCleanupService, "deleteLimit", 5_001);

        assertThatThrownBy(holdingCleanupService::validateVolumeConfiguration)
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("delete-limit must be between 1 and 5000");
    }

    @Test
    void cleanupEmptyHoldings_closeFreezePending_rejectsBeforeDelete() {
        insertHolding(1L, "OLD_EMPTY", 0, 0, NOW.minusDays(2));
        doThrow(new IllegalStateException("ledger freeze is in progress"))
                .when(marketSessionFenceService)
                .acquireMarketLedgerMutationPermit("empty holding cleanup");

        assertThatThrownBy(holdingCleanupService::cleanupEmptyHoldings)
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("ledger freeze is in progress");
        assertThat(countBySymbol("OLD_EMPTY")).isEqualTo(1);
    }

    private void insertHolding(long accountId, String symbol, long quantity, long reservedQuantity, LocalDateTime updatedAt) {
        jdbcTemplate.update(
                """
                insert into stock_holding(account_id, symbol, quantity, reserved_quantity, average_price, updated_at)
                values (?, ?, ?, ?, ?, ?)
                """,
                accountId,
                symbol,
                quantity,
                reservedQuantity,
                BigDecimal.ONE,
                updatedAt
        );
    }

    private long countBySymbol(String symbol) {
        Long count = jdbcTemplate.queryForObject(
                "select count(*) from stock_holding where symbol = ?",
                Long.class,
                symbol
        );
        return count == null ? 0 : count;
    }

    private long countAll() {
        Long count = jdbcTemplate.queryForObject("select count(*) from stock_holding", Long.class);
        return count == null ? 0 : count;
    }
}
