package stock.batch.service.marketclose.biz;

import java.time.LocalDate;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.simple.JdbcClient;

import stock.batch.service.testsupport.BatchTestDatabaseFactory;

import static org.assertj.core.api.Assertions.assertThat;

class MarketClosePostProcessingCompletionServiceTest {

    private final JdbcTemplate jdbcTemplate = new JdbcTemplate(
            BatchTestDatabaseFactory.createDataSource("market_close_post_processing_completion_test")
    );
    private final MarketClosePostProcessingCompletionService service =
            new MarketClosePostProcessingCompletionService(JdbcClient.create(jdbcTemplate));

    @BeforeEach
    void setUp() {
        jdbcTemplate.execute("drop table if exists portfolio_snapshot");
        jdbcTemplate.execute("drop table if exists stock_account");
        jdbcTemplate.execute("drop table if exists stock_market_close_run");
        jdbcTemplate.execute(
                """
                create table stock_market_close_run (
                  id bigint generated by default as identity primary key,
                  symbol varchar(20),
                  business_date date not null,
                  status varchar(20) not null
                )
                """
        );
        jdbcTemplate.execute(
                """
                create table stock_account (
                  id bigint not null primary key,
                  user_key varchar(64),
                  status varchar(20) not null
                )
                """
        );
        jdbcTemplate.execute(
                """
                create table portfolio_snapshot (
                  account_id bigint not null,
                  snapshot_date date not null
                )
                """
        );
    }

    @Test
    void isComplete_fullCloseWithoutPortfolioSnapshot_returnsFalse() {
        // given
        LocalDate businessDate = LocalDate.of(2026, 7, 3);
        insertFullCloseRun(businessDate);
        insertActiveAccount(1L, "ranker");

        // when
        boolean complete = service.isComplete(businessDate);

        // then
        assertThat(complete).isFalse();
    }

    @Test
    void isComplete_fullCloseAndPortfolioSnapshots_returnsTrue() {
        // given
        LocalDate businessDate = LocalDate.of(2026, 7, 3);
        insertFullCloseRun(businessDate);
        insertActiveAccount(1L, "ranker");
        insertPortfolioSnapshot(1L, businessDate);

        // when
        boolean complete = service.isComplete(businessDate);

        // then
        assertThat(complete).isTrue();
    }

    @Test
    void isComplete_symbolScopedCloseRun_returnsFalse() {
        // given
        LocalDate businessDate = LocalDate.of(2026, 7, 3);
        jdbcTemplate.update(
                "insert into stock_market_close_run(symbol, business_date, status) values ('DEMO001', ?, 'COMPLETED')",
                businessDate
        );

        // when
        boolean complete = service.isComplete(businessDate);

        // then
        assertThat(complete).isFalse();
    }

    private void insertFullCloseRun(LocalDate businessDate) {
        jdbcTemplate.update(
                "insert into stock_market_close_run(symbol, business_date, status) values (null, ?, 'COMPLETED')",
                businessDate
        );
    }

    private void insertActiveAccount(long accountId, String userKey) {
        jdbcTemplate.update(
                "insert into stock_account(id, user_key, status) values (?, ?, 'ACTIVE')",
                accountId,
                userKey
        );
    }

    private void insertPortfolioSnapshot(long accountId, LocalDate snapshotDate) {
        jdbcTemplate.update(
                "insert into portfolio_snapshot(account_id, snapshot_date) values (?, ?)",
                accountId,
                snapshotDate
        );
    }
}
