package stock.batch.service.marketclose.biz;

import java.time.LocalDate;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.simple.JdbcClient;

import stock.batch.service.testsupport.BatchTestDatabaseFactory;

import static org.assertj.core.api.Assertions.assertThat;

class MarketClosePostProcessingCompletionServiceTest {

    private final JdbcTemplate jdbcTemplate = new JdbcTemplate(
            BatchTestDatabaseFactory.createDataSource("market_close_post_processing_completion_test")
    );
    private final MarketClosePostProcessingCompletionService service =
            new MarketClosePostProcessingCompletionService(JdbcClient.create(jdbcTemplate));

    @BeforeEach
    void setUp() {
        jdbcTemplate.execute("drop table if exists portfolio_snapshot");
        jdbcTemplate.execute("drop table if exists stock_close_account_snapshot");
        jdbcTemplate.execute("drop table if exists stock_post_close_cycle_metric");
        jdbcTemplate.execute("drop table if exists stock_post_close_cycle");
        jdbcTemplate.execute("drop table if exists stock_market_close_run");
        jdbcTemplate.execute("""
                create table stock_market_close_run (
                  id bigint generated by default as identity primary key,
                  symbol varchar(20), business_date date not null, status varchar(20) not null
                )
                """);
        jdbcTemplate.execute("""
                create table stock_post_close_cycle (
                  id bigint primary key, business_date date not null, scope_type varchar(20),
                  scope_key varchar(40), phase varchar(60), status varchar(20), close_run_id bigint,
                  build_version varchar(100), schema_version varchar(100)
                )
                """);
        jdbcTemplate.execute("""
                create table stock_close_account_snapshot (
                  close_cycle_id bigint, account_id bigint, settlement_target boolean
                )
                """);
        jdbcTemplate.execute("""
                create table stock_post_close_cycle_metric (
                  close_cycle_id bigint primary key,
                  settlement_target_account_count bigint not null,
                  settled_account_count bigint not null,
                  settlement_missing_account_count bigint not null
                )
                """);
        jdbcTemplate.execute("""
                create table portfolio_snapshot (
                  close_cycle_id bigint, account_id bigint, input_hash varchar(64),
                  data_quality_status varchar(20)
                )
                """);
    }

    @Test
    void isComplete_frozenCycleWithoutPortfolioSnapshot_returnsFalse() {
        LocalDate businessDate = LocalDate.of(2026, 7, 3);
        insertFullCycle(businessDate, "LEDGER_FROZEN");
        insertFrozenAccount(1L);

        assertThat(service.isComplete(businessDate)).isFalse();
    }

    @Test
    void isComplete_settledCycleAndFrozenCohortSnapshots_returnsTrue() {
        LocalDate businessDate = LocalDate.of(2026, 7, 3);
        insertFullCycle(businessDate, "PORTFOLIO_SETTLED");
        insertFrozenAccount(1L);
        jdbcTemplate.update(
                "insert into portfolio_snapshot(close_cycle_id, account_id, input_hash, data_quality_status) values (10, 1, ?, 'VERIFIED')",
                "a".repeat(64)
        );
        markMetricSettled();

        assertThat(service.isComplete(businessDate)).isTrue();
    }

    @Test
    void isComplete_accountCreatedAfterFreeze_doesNotChangeCompletion() {
        LocalDate businessDate = LocalDate.of(2026, 7, 3);
        insertFullCycle(businessDate, "PORTFOLIO_SETTLED");

        assertThat(service.isComplete(businessDate)).isTrue();
    }

    @Test
    void isComplete_legacyCompletedCycleWithoutNewMetric_returnsTrue() {
        LocalDate businessDate = LocalDate.of(2026, 7, 3);
        insertFullCycle(businessDate, "COMPLETED");
        jdbcTemplate.update("delete from stock_post_close_cycle_metric where close_cycle_id = 10");
        jdbcTemplate.update(
                "update stock_post_close_cycle set build_version = null, schema_version = null where id = 10"
        );

        assertThat(service.isComplete(businessDate)).isTrue();
    }

    @Test
    void isComplete_newCompletedCycleWithoutMetric_returnsFalse() {
        LocalDate businessDate = LocalDate.of(2026, 7, 3);
        insertFullCycle(businessDate, "COMPLETED");
        jdbcTemplate.update("delete from stock_post_close_cycle_metric where close_cycle_id = 10");

        assertThat(service.isComplete(businessDate)).isFalse();
    }

    @Test
    void isComplete_symbolScopedCloseRun_returnsFalse() {
        LocalDate businessDate = LocalDate.of(2026, 7, 3);
        jdbcTemplate.update(
                "insert into stock_market_close_run(symbol, business_date, status) values ('DEMO001', ?, 'COMPLETED')",
                businessDate
        );

        assertThat(service.isComplete(businessDate)).isFalse();
    }

    private void insertFullCycle(LocalDate businessDate, String phase) {
        jdbcTemplate.update(
                "insert into stock_market_close_run(id, symbol, business_date, status) values (20, null, ?, 'COMPLETED')",
                businessDate
        );
        jdbcTemplate.update(
                """
                insert into stock_post_close_cycle(
                    id, business_date, scope_type, scope_key, phase, status, close_run_id,
                    build_version, schema_version
                ) values (10, ?, 'FULL_MARKET', 'ALL', ?, ?, 20, 'test-build', 'test-schema')
                """,
                businessDate,
                phase,
                "COMPLETED".equals(phase) ? "COMPLETED" : "PENDING"
        );
        jdbcTemplate.update(
                """
                insert into stock_post_close_cycle_metric(
                    close_cycle_id, settlement_target_account_count,
                    settled_account_count, settlement_missing_account_count
                ) values (10, 0, 0, 0)
                """
        );
    }

    private void insertFrozenAccount(long accountId) {
        jdbcTemplate.update(
                "insert into stock_close_account_snapshot(close_cycle_id, account_id, settlement_target) values (10, ?, true)",
                accountId
        );
        jdbcTemplate.update(
                """
                update stock_post_close_cycle_metric
                   set settlement_target_account_count = settlement_target_account_count + 1,
                       settlement_missing_account_count = settlement_missing_account_count + 1
                 where close_cycle_id = 10
                """
        );
    }

    private void markMetricSettled() {
        jdbcTemplate.update(
                """
                update stock_post_close_cycle_metric
                   set settled_account_count = settlement_target_account_count,
                       settlement_missing_account_count = 0
                 where close_cycle_id = 10
                """
        );
    }
}
