package stock.batch.service.automarket.profile;

public enum ProfileDecisionReason {
    SIGNAL,
    INSUFFICIENT_SIGNAL,
    ACTIVITY_DISABLED,
    INVENTORY_BELOW_TARGET,
    INVENTORY_ABOVE_TARGET,
    INVENTORY_BALANCED,
    SESSION_CLOSE,
    MULTI_DAY_SIGNAL,
    HISTORICAL_SIGNAL_UNAVAILABLE,
    PORTFOLIO_TARGET,
    LIQUIDITY_FILTER,
    FRESH_REPORT,
    REVERSAL_CONFIRMED,
    EXIT_THRESHOLD,
    HOLDING_PERIOD,
    REBALANCE_WINDOW,
    AVERAGE_DOWN,
    AVERAGE_DOWN_LIMIT,
    AVERAGE_DOWN_COOLDOWN,
    LOSS_HOLD,
    PRICE_LIMIT_TRAP,
    FUNDING_BUDGET_EMPTY,
    DIVIDEND_BUDGET_EMPTY,
    RISK_LIMIT
}
