package stock.batch.service.marketclose.model;

public enum PostClosePhase {
    OPEN,
    CLOSE_REQUESTED,
    ORDER_ENTRY_CLOSED,
    EXECUTION_DRAINED,
    LEDGER_FROZEN,
    PORTFOLIO_SETTLED,
    OVERNIGHT_CASH_APPLIED,
    CORPORATE_CASH_APPLIED,
    REPORTS_AGGREGATED,
    PREOPEN_SECURITY_TRANSFORMS_APPLIED,
    MARKET_DATA_PREPARED,
    AUTO_MARKET_PREPARED,
    READY_TO_OPEN,
    COMPLETED
}
